/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body4 model module.
* @module model/Body4
* @version 1.0.3
*/
export default class Body4 {
    /**
    * Constructs a new <code>Body4</code>.
    * @alias module:model/Body4
    * @class
    * @param data {String} 
    */

    constructor(data) {
        
        
        this['data'] = data;
        
    }

    /**
    * Constructs a <code>Body4</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body4} obj Optional instance to populate.
    * @return {module:model/Body4} The populated <code>Body4</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body4();
                        
            
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} data
    */
    'data' = undefined;




}
