/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body1 model module.
* @module model/Body1
* @version 1.0.3
*/
export default class Body1 {
    /**
    * Constructs a new <code>Body1</code>.
    * @alias module:model/Body1
    * @class
    * @param password {String} Password for authenticating
    * @param username {String} Username for authenticating
    */

    constructor(password, username) {
        
        
        this['password'] = password;
        this['username'] = username;
        
    }

    /**
    * Constructs a <code>Body1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body1} obj Optional instance to populate.
    * @return {module:model/Body1} The populated <code>Body1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body1();
                        
            
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
    * Password for authenticating
    * @member {String} password
    */
    'password' = undefined;
    /**
    * Username for authenticating
    * @member {String} username
    */
    'username' = undefined;




}
