/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GetSensorResponseUsageInfoPostStream model module.
* @module model/GetSensorResponseUsageInfoPostStream
* @version 1.0.3
*/
export default class GetSensorResponseUsageInfoPostStream {
    /**
    * Constructs a new <code>GetSensorResponseUsageInfoPostStream</code>.
    * @alias module:model/GetSensorResponseUsageInfoPostStream
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetSensorResponseUsageInfoPostStream</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetSensorResponseUsageInfoPostStream} obj Optional instance to populate.
    * @return {module:model/GetSensorResponseUsageInfoPostStream} The populated <code>GetSensorResponseUsageInfoPostStream</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSensorResponseUsageInfoPostStream();
                        
            
            if (data.hasOwnProperty('callsThisPeriod')) {
                obj['callsThisPeriod'] = ApiClient.convertToType(data['callsThisPeriod'], 'Number');
            }
            if (data.hasOwnProperty('callsTotal')) {
                obj['callsTotal'] = ApiClient.convertToType(data['callsTotal'], 'Number');
            }
            if (data.hasOwnProperty('lastCalled')) {
                obj['lastCalled'] = ApiClient.convertToType(data['lastCalled'], 'String');
            }
            if (data.hasOwnProperty('samplesThisPeriod')) {
                obj['samplesThisPeriod'] = ApiClient.convertToType(data['samplesThisPeriod'], 'Number');
            }
            if (data.hasOwnProperty('samplesTotal')) {
                obj['samplesTotal'] = ApiClient.convertToType(data['samplesTotal'], 'Number');
            }
        }
        return obj;
    }

    /**
    * number of calls to this endpoint during the current billing period
    * @member {Number} callsThisPeriod
    */
    'callsThisPeriod' = undefined;
    /**
    * total number of calls to this endpoint
    * @member {Number} callsTotal
    */
    'callsTotal' = undefined;
    /**
    * ISO formatted time of last call to this endpoint
    * @member {String} lastCalled
    */
    'lastCalled' = undefined;
    /**
    * number of samples processed during the current billing period
    * @member {Number} samplesThisPeriod
    */
    'samplesThisPeriod' = undefined;
    /**
    * total number of samples processed
    * @member {Number} samplesTotal
    */
    'samplesTotal' = undefined;




}
