/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MAmberStatus from './MAmberStatus';
import MAutotune from './MAutotune';
import MBufferStats from './MBufferStats';
import MNano from './MNano';
import MRecentAMs from './MRecentAMs';
import MRecentAnalytics from './MRecentAnalytics';
import MRecentIDs from './MRecentIDs';
import MRecentSamples from './MRecentSamples';
import MRecentTimes from './MRecentTimes';
import MStreamingParameters from './MStreamingParameters';
import MTraining from './MTraining';
import MagicNumber from './MagicNumber';
import VersionNumber from './VersionNumber';

/**
* The GetSummaryResponse model module.
* @module model/GetSummaryResponse
* @version 1.0.3
*/
export default class GetSummaryResponse {
    /**
    * Constructs a new <code>GetSummaryResponse</code>.
    * @alias module:model/GetSummaryResponse
    * @class
    * @param mNano {module:model/MNano} 
    * @param mAutotune {module:model/MAutotune} 
    * @param mAutotuningElbowClusterCounts {Array.<Number>} 
    * @param mAutotuningElbowPVArray {Array.<Number>} 
    * @param mStreamingParameters {module:model/MStreamingParameters} 
    * @param mAmberStatus {module:model/MAmberStatus} 
    * @param mTraining {module:model/MTraining} 
    * @param mAnomalyThreshold {Number} 
    * @param mAmberWarningCriticalValue {Number} 
    * @param mAmberAlertCriticalValue {Number} 
    * @param mRecentSamples {module:model/MRecentSamples} 
    * @param mRecentRawSamples {module:model/MRecentSamples} 
    * @param mRecentTimes {module:model/MRecentTimes} 
    * @param mRecentSIs {module:model/MRecentAnalytics} 
    * @param mRecentRIs {module:model/MRecentAnalytics} 
    * @param mRecentADs {module:model/MRecentAnalytics} 
    * @param mRecentAHs {module:model/MRecentAnalytics} 
    * @param mRecentAWs {module:model/MRecentAnalytics} 
    */

    constructor(mNano, mAutotune, mAutotuningElbowClusterCounts, mAutotuningElbowPVArray, mStreamingParameters, mAmberStatus, mTraining, mAnomalyThreshold, mAmberWarningCriticalValue, mAmberAlertCriticalValue, mRecentSamples, mRecentRawSamples, mRecentTimes, mRecentSIs, mRecentRIs, mRecentADs, mRecentAHs, mRecentAWs) {
        
        
        this['m_Nano'] = mNano;
        this['m_Autotune'] = mAutotune;
        this['m_AutotuningElbowClusterCounts'] = mAutotuningElbowClusterCounts;
        this['m_AutotuningElbowPVArray'] = mAutotuningElbowPVArray;
        this['m_StreamingParameters'] = mStreamingParameters;
        this['m_AmberStatus'] = mAmberStatus;
        this['m_Training'] = mTraining;
        this['m_AnomalyThreshold'] = mAnomalyThreshold;
        this['m_AmberWarningCriticalValue'] = mAmberWarningCriticalValue;
        this['m_AmberAlertCriticalValue'] = mAmberAlertCriticalValue;
        this['m_RecentSamples'] = mRecentSamples;
        this['m_RecentRawSamples'] = mRecentRawSamples;
        this['m_RecentTimes'] = mRecentTimes;
        this['m_RecentSIs'] = mRecentSIs;
        this['m_RecentRIs'] = mRecentRIs;
        this['m_RecentADs'] = mRecentADs;
        this['m_RecentAHs'] = mRecentAHs;
        this['m_RecentAWs'] = mRecentAWs;
        
    }

    /**
    * Constructs a <code>GetSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetSummaryResponse} obj Optional instance to populate.
    * @return {module:model/GetSummaryResponse} The populated <code>GetSummaryResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSummaryResponse();
                        
            
            if (data.hasOwnProperty('MagicNumber')) {
                obj['MagicNumber'] = MagicNumber.constructFromObject(data['MagicNumber']);
            }
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_Nano')) {
                obj['m_Nano'] = MNano.constructFromObject(data['m_Nano']);
            }
            if (data.hasOwnProperty('m_BufferStats')) {
                obj['m_BufferStats'] = MBufferStats.constructFromObject(data['m_BufferStats']);
            }
            if (data.hasOwnProperty('m_Autotune')) {
                obj['m_Autotune'] = MAutotune.constructFromObject(data['m_Autotune']);
            }
            if (data.hasOwnProperty('m_AutotuningElbowClusterCounts')) {
                obj['m_AutotuningElbowClusterCounts'] = ApiClient.convertToType(data['m_AutotuningElbowClusterCounts'], ['Number']);
            }
            if (data.hasOwnProperty('m_AutotuningElbowPVArray')) {
                obj['m_AutotuningElbowPVArray'] = ApiClient.convertToType(data['m_AutotuningElbowPVArray'], ['Number']);
            }
            if (data.hasOwnProperty('m_StreamingParameters')) {
                obj['m_StreamingParameters'] = MStreamingParameters.constructFromObject(data['m_StreamingParameters']);
            }
            if (data.hasOwnProperty('m_AmberStatus')) {
                obj['m_AmberStatus'] = MAmberStatus.constructFromObject(data['m_AmberStatus']);
            }
            if (data.hasOwnProperty('m_Training')) {
                obj['m_Training'] = MTraining.constructFromObject(data['m_Training']);
            }
            if (data.hasOwnProperty('m_AnomalyThreshold')) {
                obj['m_AnomalyThreshold'] = ApiClient.convertToType(data['m_AnomalyThreshold'], 'Number');
            }
            if (data.hasOwnProperty('m_AmberWarningCriticalValue')) {
                obj['m_AmberWarningCriticalValue'] = ApiClient.convertToType(data['m_AmberWarningCriticalValue'], 'Number');
            }
            if (data.hasOwnProperty('m_AmberAlertCriticalValue')) {
                obj['m_AmberAlertCriticalValue'] = ApiClient.convertToType(data['m_AmberAlertCriticalValue'], 'Number');
            }
            if (data.hasOwnProperty('m_ErrorStringBuffer')) {
                obj['m_ErrorStringBuffer'] = ApiClient.convertToType(data['m_ErrorStringBuffer'], 'String');
            }
            if (data.hasOwnProperty('m_ClusteringParametersInitialized')) {
                obj['m_ClusteringParametersInitialized'] = ApiClient.convertToType(data['m_ClusteringParametersInitialized'], 'Boolean');
            }
            if (data.hasOwnProperty('m_StreamingMode')) {
                obj['m_StreamingMode'] = ApiClient.convertToType(data['m_StreamingMode'], 'Boolean');
            }
            if (data.hasOwnProperty('m_StreamingModeStatus')) {
                obj['m_StreamingModeStatus'] = ApiClient.convertToType(data['m_StreamingModeStatus'], 'Number');
            }
            if (data.hasOwnProperty('m_ModifiedAt')) {
                obj['m_ModifiedAt'] = ApiClient.convertToType(data['m_ModifiedAt'], 'Number');
            }
            if (data.hasOwnProperty('m_AnomalyMetricByAnomalyCount')) {
                obj['m_AnomalyMetricByAnomalyCount'] = ApiClient.convertToType(data['m_AnomalyMetricByAnomalyCount'], ['Number']);
            }
            if (data.hasOwnProperty('m_RecentAnomalyCount')) {
                obj['m_RecentAnomalyCount'] = ApiClient.convertToType(data['m_RecentAnomalyCount'], 'Number');
            }
            if (data.hasOwnProperty('m_ResultsIDArray')) {
                obj['m_ResultsIDArray'] = ApiClient.convertToType(data['m_ResultsIDArray'], ['Number']);
            }
            if (data.hasOwnProperty('m_TrainingSamples')) {
                obj['m_TrainingSamples'] = MRecentSamples.constructFromObject(data['m_TrainingSamples']);
            }
            if (data.hasOwnProperty('m_RecentSamples')) {
                obj['m_RecentSamples'] = MRecentSamples.constructFromObject(data['m_RecentSamples']);
            }
            if (data.hasOwnProperty('m_RecentRawSamples')) {
                obj['m_RecentRawSamples'] = MRecentSamples.constructFromObject(data['m_RecentRawSamples']);
            }
            if (data.hasOwnProperty('m_RecentTimes')) {
                obj['m_RecentTimes'] = MRecentTimes.constructFromObject(data['m_RecentTimes']);
            }
            if (data.hasOwnProperty('m_RecentSIs')) {
                obj['m_RecentSIs'] = MRecentAnalytics.constructFromObject(data['m_RecentSIs']);
            }
            if (data.hasOwnProperty('m_RecentRIs')) {
                obj['m_RecentRIs'] = MRecentAnalytics.constructFromObject(data['m_RecentRIs']);
            }
            if (data.hasOwnProperty('m_RecentADs')) {
                obj['m_RecentADs'] = MRecentAnalytics.constructFromObject(data['m_RecentADs']);
            }
            if (data.hasOwnProperty('m_RecentAHs')) {
                obj['m_RecentAHs'] = MRecentAnalytics.constructFromObject(data['m_RecentAHs']);
            }
            if (data.hasOwnProperty('m_RecentIDs')) {
                obj['m_RecentIDs'] = MRecentIDs.constructFromObject(data['m_RecentIDs']);
            }
            if (data.hasOwnProperty('m_RecentAMs')) {
                obj['m_RecentAMs'] = MRecentAMs.constructFromObject(data['m_RecentAMs']);
            }
            if (data.hasOwnProperty('m_RecentAWs')) {
                obj['m_RecentAWs'] = MRecentAnalytics.constructFromObject(data['m_RecentAWs']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MagicNumber} MagicNumber
    */
    'MagicNumber' = undefined;
    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {module:model/MNano} m_Nano
    */
    'm_Nano' = undefined;
    /**
    * @member {module:model/MBufferStats} m_BufferStats
    */
    'm_BufferStats' = undefined;
    /**
    * @member {module:model/MAutotune} m_Autotune
    */
    'm_Autotune' = undefined;
    /**
    * @member {Array.<Number>} m_AutotuningElbowClusterCounts
    */
    'm_AutotuningElbowClusterCounts' = undefined;
    /**
    * @member {Array.<Number>} m_AutotuningElbowPVArray
    */
    'm_AutotuningElbowPVArray' = undefined;
    /**
    * @member {module:model/MStreamingParameters} m_StreamingParameters
    */
    'm_StreamingParameters' = undefined;
    /**
    * @member {module:model/MAmberStatus} m_AmberStatus
    */
    'm_AmberStatus' = undefined;
    /**
    * @member {module:model/MTraining} m_Training
    */
    'm_Training' = undefined;
    /**
    * @member {Number} m_AnomalyThreshold
    */
    'm_AnomalyThreshold' = undefined;
    /**
    * @member {Number} m_AmberWarningCriticalValue
    */
    'm_AmberWarningCriticalValue' = undefined;
    /**
    * @member {Number} m_AmberAlertCriticalValue
    */
    'm_AmberAlertCriticalValue' = undefined;
    /**
    * @member {String} m_ErrorStringBuffer
    */
    'm_ErrorStringBuffer' = undefined;
    /**
    * @member {Boolean} m_ClusteringParametersInitialized
    */
    'm_ClusteringParametersInitialized' = undefined;
    /**
    * @member {Boolean} m_StreamingMode
    */
    'm_StreamingMode' = undefined;
    /**
    * @member {Number} m_StreamingModeStatus
    */
    'm_StreamingModeStatus' = undefined;
    /**
    * @member {Number} m_ModifiedAt
    */
    'm_ModifiedAt' = undefined;
    /**
    * @member {Array.<Number>} m_AnomalyMetricByAnomalyCount
    */
    'm_AnomalyMetricByAnomalyCount' = undefined;
    /**
    * @member {Number} m_RecentAnomalyCount
    */
    'm_RecentAnomalyCount' = undefined;
    /**
    * @member {Array.<Number>} m_ResultsIDArray
    */
    'm_ResultsIDArray' = undefined;
    /**
    * @member {module:model/MRecentSamples} m_TrainingSamples
    */
    'm_TrainingSamples' = undefined;
    /**
    * @member {module:model/MRecentSamples} m_RecentSamples
    */
    'm_RecentSamples' = undefined;
    /**
    * @member {module:model/MRecentSamples} m_RecentRawSamples
    */
    'm_RecentRawSamples' = undefined;
    /**
    * @member {module:model/MRecentTimes} m_RecentTimes
    */
    'm_RecentTimes' = undefined;
    /**
    * @member {module:model/MRecentAnalytics} m_RecentSIs
    */
    'm_RecentSIs' = undefined;
    /**
    * @member {module:model/MRecentAnalytics} m_RecentRIs
    */
    'm_RecentRIs' = undefined;
    /**
    * @member {module:model/MRecentAnalytics} m_RecentADs
    */
    'm_RecentADs' = undefined;
    /**
    * @member {module:model/MRecentAnalytics} m_RecentAHs
    */
    'm_RecentAHs' = undefined;
    /**
    * @member {module:model/MRecentIDs} m_RecentIDs
    */
    'm_RecentIDs' = undefined;
    /**
    * @member {module:model/MRecentAMs} m_RecentAMs
    */
    'm_RecentAMs' = undefined;
    /**
    * @member {module:model/MRecentAnalytics} m_RecentAWs
    */
    'm_RecentAWs' = undefined;




}
