/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MAmberStatus} from './MAmberStatus';
import {MAutotune} from './MAutotune';
import {MBufferStats} from './MBufferStats';
import {MNano} from './MNano';
import {MRecentAMs} from './MRecentAMs';
import {MRecentAnalytics} from './MRecentAnalytics';
import {MRecentIDs} from './MRecentIDs';
import {MRecentSamples} from './MRecentSamples';
import {MRecentTimes} from './MRecentTimes';
import {MStreamingParameters} from './MStreamingParameters';
import {MTraining} from './MTraining';
import {MagicNumber} from './MagicNumber';
import {VersionNumber} from './VersionNumber';

/**
 * The GetSummaryResponse model module.
 * @module model/GetSummaryResponse
 * @version 1.0.3
 */
export class GetSummaryResponse {
  /**
   * Constructs a new <code>GetSummaryResponse</code>.
   * @alias module:model/GetSummaryResponse
   * @class
   * @param mNano {module:model/MNano} 
   * @param mAutotune {module:model/MAutotune} 
   * @param mAutotuningElbowClusterCounts {Array.<Number>} 
   * @param mAutotuningElbowPVArray {Array.<Number>} 
   * @param mStreamingParameters {module:model/MStreamingParameters} 
   * @param mAmberStatus {module:model/MAmberStatus} 
   * @param mTraining {module:model/MTraining} 
   * @param mAnomalyThreshold {Number} 
   * @param mAmberWarningCriticalValue {Number} 
   * @param mAmberAlertCriticalValue {Number} 
   * @param mRecentSamples {module:model/MRecentSamples} 
   * @param mRecentRawSamples {module:model/MRecentSamples} 
   * @param mRecentTimes {module:model/MRecentTimes} 
   * @param mRecentSIs {module:model/MRecentAnalytics} 
   * @param mRecentRIs {module:model/MRecentAnalytics} 
   * @param mRecentADs {module:model/MRecentAnalytics} 
   * @param mRecentAHs {module:model/MRecentAnalytics} 
   * @param mRecentAWs {module:model/MRecentAnalytics} 
   */
  constructor(mNano, mAutotune, mAutotuningElbowClusterCounts, mAutotuningElbowPVArray, mStreamingParameters, mAmberStatus, mTraining, mAnomalyThreshold, mAmberWarningCriticalValue, mAmberAlertCriticalValue, mRecentSamples, mRecentRawSamples, mRecentTimes, mRecentSIs, mRecentRIs, mRecentADs, mRecentAHs, mRecentAWs) {
    this.mNano = mNano;
    this.mAutotune = mAutotune;
    this.mAutotuningElbowClusterCounts = mAutotuningElbowClusterCounts;
    this.mAutotuningElbowPVArray = mAutotuningElbowPVArray;
    this.mStreamingParameters = mStreamingParameters;
    this.mAmberStatus = mAmberStatus;
    this.mTraining = mTraining;
    this.mAnomalyThreshold = mAnomalyThreshold;
    this.mAmberWarningCriticalValue = mAmberWarningCriticalValue;
    this.mAmberAlertCriticalValue = mAmberAlertCriticalValue;
    this.mRecentSamples = mRecentSamples;
    this.mRecentRawSamples = mRecentRawSamples;
    this.mRecentTimes = mRecentTimes;
    this.mRecentSIs = mRecentSIs;
    this.mRecentRIs = mRecentRIs;
    this.mRecentADs = mRecentADs;
    this.mRecentAHs = mRecentAHs;
    this.mRecentAWs = mRecentAWs;
  }

  /**
   * Constructs a <code>GetSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetSummaryResponse} obj Optional instance to populate.
   * @return {module:model/GetSummaryResponse} The populated <code>GetSummaryResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetSummaryResponse();
      if (data.hasOwnProperty('MagicNumber'))
        obj.magicNumber = MagicNumber.constructFromObject(data['MagicNumber']);
      if (data.hasOwnProperty('VersionNumber'))
        obj.versionNumber = VersionNumber.constructFromObject(data['VersionNumber']);
      if (data.hasOwnProperty('m_Nano'))
        obj.mNano = MNano.constructFromObject(data['m_Nano']);
      if (data.hasOwnProperty('m_BufferStats'))
        obj.mBufferStats = MBufferStats.constructFromObject(data['m_BufferStats']);
      if (data.hasOwnProperty('m_Autotune'))
        obj.mAutotune = MAutotune.constructFromObject(data['m_Autotune']);
      if (data.hasOwnProperty('m_AutotuningElbowClusterCounts'))
        obj.mAutotuningElbowClusterCounts = ApiClient.convertToType(data['m_AutotuningElbowClusterCounts'], ['Number']);
      if (data.hasOwnProperty('m_AutotuningElbowPVArray'))
        obj.mAutotuningElbowPVArray = ApiClient.convertToType(data['m_AutotuningElbowPVArray'], ['Number']);
      if (data.hasOwnProperty('m_StreamingParameters'))
        obj.mStreamingParameters = MStreamingParameters.constructFromObject(data['m_StreamingParameters']);
      if (data.hasOwnProperty('m_AmberStatus'))
        obj.mAmberStatus = MAmberStatus.constructFromObject(data['m_AmberStatus']);
      if (data.hasOwnProperty('m_Training'))
        obj.mTraining = MTraining.constructFromObject(data['m_Training']);
      if (data.hasOwnProperty('m_AnomalyThreshold'))
        obj.mAnomalyThreshold = ApiClient.convertToType(data['m_AnomalyThreshold'], 'Number');
      if (data.hasOwnProperty('m_AmberWarningCriticalValue'))
        obj.mAmberWarningCriticalValue = ApiClient.convertToType(data['m_AmberWarningCriticalValue'], 'Number');
      if (data.hasOwnProperty('m_AmberAlertCriticalValue'))
        obj.mAmberAlertCriticalValue = ApiClient.convertToType(data['m_AmberAlertCriticalValue'], 'Number');
      if (data.hasOwnProperty('m_ErrorStringBuffer'))
        obj.mErrorStringBuffer = ApiClient.convertToType(data['m_ErrorStringBuffer'], 'String');
      if (data.hasOwnProperty('m_ClusteringParametersInitialized'))
        obj.mClusteringParametersInitialized = ApiClient.convertToType(data['m_ClusteringParametersInitialized'], 'Boolean');
      if (data.hasOwnProperty('m_StreamingMode'))
        obj.mStreamingMode = ApiClient.convertToType(data['m_StreamingMode'], 'Boolean');
      if (data.hasOwnProperty('m_StreamingModeStatus'))
        obj.mStreamingModeStatus = ApiClient.convertToType(data['m_StreamingModeStatus'], 'Number');
      if (data.hasOwnProperty('m_ModifiedAt'))
        obj.mModifiedAt = ApiClient.convertToType(data['m_ModifiedAt'], 'Number');
      if (data.hasOwnProperty('m_AnomalyMetricByAnomalyCount'))
        obj.mAnomalyMetricByAnomalyCount = ApiClient.convertToType(data['m_AnomalyMetricByAnomalyCount'], ['Number']);
      if (data.hasOwnProperty('m_RecentAnomalyCount'))
        obj.mRecentAnomalyCount = ApiClient.convertToType(data['m_RecentAnomalyCount'], 'Number');
      if (data.hasOwnProperty('m_ResultsIDArray'))
        obj.mResultsIDArray = ApiClient.convertToType(data['m_ResultsIDArray'], ['Number']);
      if (data.hasOwnProperty('m_TrainingSamples'))
        obj.mTrainingSamples = MRecentSamples.constructFromObject(data['m_TrainingSamples']);
      if (data.hasOwnProperty('m_RecentSamples'))
        obj.mRecentSamples = MRecentSamples.constructFromObject(data['m_RecentSamples']);
      if (data.hasOwnProperty('m_RecentRawSamples'))
        obj.mRecentRawSamples = MRecentSamples.constructFromObject(data['m_RecentRawSamples']);
      if (data.hasOwnProperty('m_RecentTimes'))
        obj.mRecentTimes = MRecentTimes.constructFromObject(data['m_RecentTimes']);
      if (data.hasOwnProperty('m_RecentSIs'))
        obj.mRecentSIs = MRecentAnalytics.constructFromObject(data['m_RecentSIs']);
      if (data.hasOwnProperty('m_RecentRIs'))
        obj.mRecentRIs = MRecentAnalytics.constructFromObject(data['m_RecentRIs']);
      if (data.hasOwnProperty('m_RecentADs'))
        obj.mRecentADs = MRecentAnalytics.constructFromObject(data['m_RecentADs']);
      if (data.hasOwnProperty('m_RecentAHs'))
        obj.mRecentAHs = MRecentAnalytics.constructFromObject(data['m_RecentAHs']);
      if (data.hasOwnProperty('m_RecentIDs'))
        obj.mRecentIDs = MRecentIDs.constructFromObject(data['m_RecentIDs']);
      if (data.hasOwnProperty('m_RecentAMs'))
        obj.mRecentAMs = MRecentAMs.constructFromObject(data['m_RecentAMs']);
      if (data.hasOwnProperty('m_RecentAWs'))
        obj.mRecentAWs = MRecentAnalytics.constructFromObject(data['m_RecentAWs']);
    }
    return obj;
  }
}

/**
 * @member {module:model/MagicNumber} magicNumber
 */
GetSummaryResponse.prototype.magicNumber = undefined;

/**
 * @member {module:model/VersionNumber} versionNumber
 */
GetSummaryResponse.prototype.versionNumber = undefined;

/**
 * @member {module:model/MNano} mNano
 */
GetSummaryResponse.prototype.mNano = undefined;

/**
 * @member {module:model/MBufferStats} mBufferStats
 */
GetSummaryResponse.prototype.mBufferStats = undefined;

/**
 * @member {module:model/MAutotune} mAutotune
 */
GetSummaryResponse.prototype.mAutotune = undefined;

/**
 * @member {Array.<Number>} mAutotuningElbowClusterCounts
 */
GetSummaryResponse.prototype.mAutotuningElbowClusterCounts = undefined;

/**
 * @member {Array.<Number>} mAutotuningElbowPVArray
 */
GetSummaryResponse.prototype.mAutotuningElbowPVArray = undefined;

/**
 * @member {module:model/MStreamingParameters} mStreamingParameters
 */
GetSummaryResponse.prototype.mStreamingParameters = undefined;

/**
 * @member {module:model/MAmberStatus} mAmberStatus
 */
GetSummaryResponse.prototype.mAmberStatus = undefined;

/**
 * @member {module:model/MTraining} mTraining
 */
GetSummaryResponse.prototype.mTraining = undefined;

/**
 * @member {Number} mAnomalyThreshold
 */
GetSummaryResponse.prototype.mAnomalyThreshold = undefined;

/**
 * @member {Number} mAmberWarningCriticalValue
 */
GetSummaryResponse.prototype.mAmberWarningCriticalValue = undefined;

/**
 * @member {Number} mAmberAlertCriticalValue
 */
GetSummaryResponse.prototype.mAmberAlertCriticalValue = undefined;

/**
 * @member {String} mErrorStringBuffer
 */
GetSummaryResponse.prototype.mErrorStringBuffer = undefined;

/**
 * @member {Boolean} mClusteringParametersInitialized
 */
GetSummaryResponse.prototype.mClusteringParametersInitialized = undefined;

/**
 * @member {Boolean} mStreamingMode
 */
GetSummaryResponse.prototype.mStreamingMode = undefined;

/**
 * @member {Number} mStreamingModeStatus
 */
GetSummaryResponse.prototype.mStreamingModeStatus = undefined;

/**
 * @member {Number} mModifiedAt
 */
GetSummaryResponse.prototype.mModifiedAt = undefined;

/**
 * @member {Array.<Number>} mAnomalyMetricByAnomalyCount
 */
GetSummaryResponse.prototype.mAnomalyMetricByAnomalyCount = undefined;

/**
 * @member {Number} mRecentAnomalyCount
 */
GetSummaryResponse.prototype.mRecentAnomalyCount = undefined;

/**
 * @member {Array.<Number>} mResultsIDArray
 */
GetSummaryResponse.prototype.mResultsIDArray = undefined;

/**
 * @member {module:model/MRecentSamples} mTrainingSamples
 */
GetSummaryResponse.prototype.mTrainingSamples = undefined;

/**
 * @member {module:model/MRecentSamples} mRecentSamples
 */
GetSummaryResponse.prototype.mRecentSamples = undefined;

/**
 * @member {module:model/MRecentSamples} mRecentRawSamples
 */
GetSummaryResponse.prototype.mRecentRawSamples = undefined;

/**
 * @member {module:model/MRecentTimes} mRecentTimes
 */
GetSummaryResponse.prototype.mRecentTimes = undefined;

/**
 * @member {module:model/MRecentAnalytics} mRecentSIs
 */
GetSummaryResponse.prototype.mRecentSIs = undefined;

/**
 * @member {module:model/MRecentAnalytics} mRecentRIs
 */
GetSummaryResponse.prototype.mRecentRIs = undefined;

/**
 * @member {module:model/MRecentAnalytics} mRecentADs
 */
GetSummaryResponse.prototype.mRecentADs = undefined;

/**
 * @member {module:model/MRecentAnalytics} mRecentAHs
 */
GetSummaryResponse.prototype.mRecentAHs = undefined;

/**
 * @member {module:model/MRecentIDs} mRecentIDs
 */
GetSummaryResponse.prototype.mRecentIDs = undefined;

/**
 * @member {module:model/MRecentAMs} mRecentAMs
 */
GetSummaryResponse.prototype.mRecentAMs = undefined;

/**
 * @member {module:model/MRecentAnalytics} mRecentAWs
 */
GetSummaryResponse.prototype.mRecentAWs = undefined;

