/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetSensorResponseUsageInfoGetConfig from './GetSensorResponseUsageInfoGetConfig';
import GetSensorResponseUsageInfoPostStream from './GetSensorResponseUsageInfoPostStream';

/**
* The GetSensorResponseUsageInfo model module.
* @module model/GetSensorResponseUsageInfo
* @version 1.0.3
*/
export default class GetSensorResponseUsageInfo {
    /**
    * Constructs a new <code>GetSensorResponseUsageInfo</code>.
    * @alias module:model/GetSensorResponseUsageInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetSensorResponseUsageInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetSensorResponseUsageInfo} obj Optional instance to populate.
    * @return {module:model/GetSensorResponseUsageInfo} The populated <code>GetSensorResponseUsageInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSensorResponseUsageInfo();
                        
            
            if (data.hasOwnProperty('getConfig')) {
                obj['getConfig'] = GetSensorResponseUsageInfoGetConfig.constructFromObject(data['getConfig']);
            }
            if (data.hasOwnProperty('getSensor')) {
                obj['getSensor'] = GetSensorResponseUsageInfoGetConfig.constructFromObject(data['getSensor']);
            }
            if (data.hasOwnProperty('getStatus')) {
                obj['getStatus'] = GetSensorResponseUsageInfoGetConfig.constructFromObject(data['getStatus']);
            }
            if (data.hasOwnProperty('postConfig')) {
                obj['postConfig'] = GetSensorResponseUsageInfoGetConfig.constructFromObject(data['postConfig']);
            }
            if (data.hasOwnProperty('postStream')) {
                obj['postStream'] = GetSensorResponseUsageInfoPostStream.constructFromObject(data['postStream']);
            }
            if (data.hasOwnProperty('putSensor')) {
                obj['putSensor'] = GetSensorResponseUsageInfoGetConfig.constructFromObject(data['putSensor']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/GetSensorResponseUsageInfoGetConfig} getConfig
    */
    'getConfig' = undefined;
    /**
    * @member {module:model/GetSensorResponseUsageInfoGetConfig} getSensor
    */
    'getSensor' = undefined;
    /**
    * @member {module:model/GetSensorResponseUsageInfoGetConfig} getStatus
    */
    'getStatus' = undefined;
    /**
    * @member {module:model/GetSensorResponseUsageInfoGetConfig} postConfig
    */
    'postConfig' = undefined;
    /**
    * @member {module:model/GetSensorResponseUsageInfoPostStream} postStream
    */
    'postStream' = undefined;
    /**
    * @member {module:model/GetSensorResponseUsageInfoGetConfig} putSensor
    */
    'putSensor' = undefined;




}
