/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VersionNumber} from './VersionNumber';

/**
 * The MAmberStatus model module.
 * @module model/MAmberStatus
 * @version 1.0.3
 */
export class MAmberStatus {
  /**
   * Constructs a new <code>MAmberStatus</code>.
   * @alias module:model/MAmberStatus
   * @class
   * @param mStatus {String} 
   * @param mCurrentClusterCount {Number} 
   * @param mRetryCount {Number} 
   * @param mStreamingWindowSize {Number} 
   * @param mTotalInferences {Number} 
   */
  constructor(mStatus, mCurrentClusterCount, mRetryCount, mStreamingWindowSize, mTotalInferences) {
    this.mStatus = mStatus;
    this.mCurrentClusterCount = mCurrentClusterCount;
    this.mRetryCount = mRetryCount;
    this.mStreamingWindowSize = mStreamingWindowSize;
    this.mTotalInferences = mTotalInferences;
  }

  /**
   * Constructs a <code>MAmberStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MAmberStatus} obj Optional instance to populate.
   * @return {module:model/MAmberStatus} The populated <code>MAmberStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MAmberStatus();
      if (data.hasOwnProperty('VersionNumber'))
        obj.versionNumber = VersionNumber.constructFromObject(data['VersionNumber']);
      if (data.hasOwnProperty('m_Status'))
        obj.mStatus = ApiClient.convertToType(data['m_Status'], 'String');
      if (data.hasOwnProperty('m_Message'))
        obj.mMessage = ApiClient.convertToType(data['m_Message'], 'String');
      if (data.hasOwnProperty('m_Progress'))
        obj.mProgress = ApiClient.convertToType(data['m_Progress'], 'Number');
      if (data.hasOwnProperty('m_CurrentClusterCount'))
        obj.mCurrentClusterCount = ApiClient.convertToType(data['m_CurrentClusterCount'], 'Number');
      if (data.hasOwnProperty('m_RetryCount'))
        obj.mRetryCount = ApiClient.convertToType(data['m_RetryCount'], 'Number');
      if (data.hasOwnProperty('m_StreamingWindowSize'))
        obj.mStreamingWindowSize = ApiClient.convertToType(data['m_StreamingWindowSize'], 'Number');
      if (data.hasOwnProperty('m_TotalInferences'))
        obj.mTotalInferences = ApiClient.convertToType(data['m_TotalInferences'], 'Number');
      if (data.hasOwnProperty('m_TotalSamplesWritten'))
        obj.mTotalSamplesWritten = ApiClient.convertToType(data['m_TotalSamplesWritten'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/VersionNumber} versionNumber
 */
MAmberStatus.prototype.versionNumber = undefined;

/**
 * @member {String} mStatus
 */
MAmberStatus.prototype.mStatus = undefined;

/**
 * @member {String} mMessage
 */
MAmberStatus.prototype.mMessage = undefined;

/**
 * @member {Number} mProgress
 */
MAmberStatus.prototype.mProgress = undefined;

/**
 * @member {Number} mCurrentClusterCount
 */
MAmberStatus.prototype.mCurrentClusterCount = undefined;

/**
 * @member {Number} mRetryCount
 */
MAmberStatus.prototype.mRetryCount = undefined;

/**
 * @member {Number} mStreamingWindowSize
 */
MAmberStatus.prototype.mStreamingWindowSize = undefined;

/**
 * @member {Number} mTotalInferences
 */
MAmberStatus.prototype.mTotalInferences = undefined;

/**
 * @member {Number} mTotalSamplesWritten
 */
MAmberStatus.prototype.mTotalSamplesWritten = undefined;

