/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VersionNumber from './VersionNumber';

/**
* The MAmberStatus model module.
* @module model/MAmberStatus
* @version 1.0.3
*/
export default class MAmberStatus {
    /**
    * Constructs a new <code>MAmberStatus</code>.
    * @alias module:model/MAmberStatus
    * @class
    * @param mStatus {String} 
    * @param mCurrentClusterCount {Number} 
    * @param mRetryCount {Number} 
    * @param mStreamingWindowSize {Number} 
    * @param mTotalInferences {Number} 
    */

    constructor(mStatus, mCurrentClusterCount, mRetryCount, mStreamingWindowSize, mTotalInferences) {
        
        
        this['m_Status'] = mStatus;
        this['m_CurrentClusterCount'] = mCurrentClusterCount;
        this['m_RetryCount'] = mRetryCount;
        this['m_StreamingWindowSize'] = mStreamingWindowSize;
        this['m_TotalInferences'] = mTotalInferences;
        
    }

    /**
    * Constructs a <code>MAmberStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MAmberStatus} obj Optional instance to populate.
    * @return {module:model/MAmberStatus} The populated <code>MAmberStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MAmberStatus();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_Status')) {
                obj['m_Status'] = ApiClient.convertToType(data['m_Status'], 'String');
            }
            if (data.hasOwnProperty('m_Message')) {
                obj['m_Message'] = ApiClient.convertToType(data['m_Message'], 'String');
            }
            if (data.hasOwnProperty('m_Progress')) {
                obj['m_Progress'] = ApiClient.convertToType(data['m_Progress'], 'Number');
            }
            if (data.hasOwnProperty('m_CurrentClusterCount')) {
                obj['m_CurrentClusterCount'] = ApiClient.convertToType(data['m_CurrentClusterCount'], 'Number');
            }
            if (data.hasOwnProperty('m_RetryCount')) {
                obj['m_RetryCount'] = ApiClient.convertToType(data['m_RetryCount'], 'Number');
            }
            if (data.hasOwnProperty('m_StreamingWindowSize')) {
                obj['m_StreamingWindowSize'] = ApiClient.convertToType(data['m_StreamingWindowSize'], 'Number');
            }
            if (data.hasOwnProperty('m_TotalInferences')) {
                obj['m_TotalInferences'] = ApiClient.convertToType(data['m_TotalInferences'], 'Number');
            }
            if (data.hasOwnProperty('m_TotalSamplesWritten')) {
                obj['m_TotalSamplesWritten'] = ApiClient.convertToType(data['m_TotalSamplesWritten'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {String} m_Status
    */
    'm_Status' = undefined;
    /**
    * @member {String} m_Message
    */
    'm_Message' = undefined;
    /**
    * @member {Number} m_Progress
    */
    'm_Progress' = undefined;
    /**
    * @member {Number} m_CurrentClusterCount
    */
    'm_CurrentClusterCount' = undefined;
    /**
    * @member {Number} m_RetryCount
    */
    'm_RetryCount' = undefined;
    /**
    * @member {Number} m_StreamingWindowSize
    */
    'm_StreamingWindowSize' = undefined;
    /**
    * @member {Number} m_TotalInferences
    */
    'm_TotalInferences' = undefined;
    /**
    * @member {Number} m_TotalSamplesWritten
    */
    'm_TotalSamplesWritten' = undefined;




}
