/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VersionNumber from './VersionNumber';

/**
* The MAP model module.
* @module model/MAP
* @version 1.0.3
*/
export default class MAP {
    /**
    * Constructs a new <code>MAP</code>.
    * @alias module:model/MAP
    * @class
    * @param mAutotuneRange {Boolean} 
    * @param mAutotunePV {Boolean} 
    * @param mAutotuneByFeatures {Boolean} 
    */

    constructor(mAutotuneRange, mAutotunePV, mAutotuneByFeatures) {
        
        
        this['m_AutotuneRange'] = mAutotuneRange;
        this['m_AutotunePV'] = mAutotunePV;
        this['m_AutotuneByFeatures'] = mAutotuneByFeatures;
        
    }

    /**
    * Constructs a <code>MAP</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MAP} obj Optional instance to populate.
    * @return {module:model/MAP} The populated <code>MAP</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MAP();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_AutotuneRange')) {
                obj['m_AutotuneRange'] = ApiClient.convertToType(data['m_AutotuneRange'], 'Boolean');
            }
            if (data.hasOwnProperty('m_AutotunePV')) {
                obj['m_AutotunePV'] = ApiClient.convertToType(data['m_AutotunePV'], 'Boolean');
            }
            if (data.hasOwnProperty('m_AutotuneByFeatures')) {
                obj['m_AutotuneByFeatures'] = ApiClient.convertToType(data['m_AutotuneByFeatures'], 'Boolean');
            }
            if (data.hasOwnProperty('m_MaxClusters')) {
                obj['m_MaxClusters'] = ApiClient.convertToType(data['m_MaxClusters'], 'Number');
            }
            if (data.hasOwnProperty('m_FeaturesToTuneArray')) {
                obj['m_FeaturesToTuneArray'] = ApiClient.convertToType(data['m_FeaturesToTuneArray'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {Boolean} m_AutotuneRange
    */
    'm_AutotuneRange' = undefined;
    /**
    * @member {Boolean} m_AutotunePV
    */
    'm_AutotunePV' = undefined;
    /**
    * @member {Boolean} m_AutotuneByFeatures
    */
    'm_AutotuneByFeatures' = undefined;
    /**
    * @member {Number} m_MaxClusters
    */
    'm_MaxClusters' = undefined;
    /**
    * @member {Array.<Number>} m_FeaturesToTuneArray
    */
    'm_FeaturesToTuneArray' = undefined;




}
