/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MAP from './MAP';
import MNCP from './MNCP';
import VersionNumber from './VersionNumber';

/**
* The MAutotune model module.
* @module model/MAutotune
* @version 1.0.3
*/
export default class MAutotune {
    /**
    * Constructs a new <code>MAutotune</code>.
    * @alias module:model/MAutotune
    * @class
    * @param mAP {module:model/MAP} 
    */

    constructor(mAP) {
        
        
        this['m_AP'] = mAP;
        
    }

    /**
    * Constructs a <code>MAutotune</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MAutotune} obj Optional instance to populate.
    * @return {module:model/MAutotune} The populated <code>MAutotune</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MAutotune();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_AutotuningInProgress')) {
                obj['m_AutotuningInProgress'] = ApiClient.convertToType(data['m_AutotuningInProgress'], 'Boolean');
            }
            if (data.hasOwnProperty('m_PercentComplete')) {
                obj['m_PercentComplete'] = ApiClient.convertToType(data['m_PercentComplete'], 'Number');
            }
            if (data.hasOwnProperty('m_AutotuningSucceeded')) {
                obj['m_AutotuningSucceeded'] = ApiClient.convertToType(data['m_AutotuningSucceeded'], 'Boolean');
            }
            if (data.hasOwnProperty('m_NumPatternsToAutotune')) {
                obj['m_NumPatternsToAutotune'] = ApiClient.convertToType(data['m_NumPatternsToAutotune'], 'Number');
            }
            if (data.hasOwnProperty('m_ErrorStringBuffer')) {
                obj['m_ErrorStringBuffer'] = ApiClient.convertToType(data['m_ErrorStringBuffer'], 'String');
            }
            if (data.hasOwnProperty('m_FeaturesToTuneArray')) {
                obj['m_FeaturesToTuneArray'] = ApiClient.convertToType(data['m_FeaturesToTuneArray'], ['Boolean']);
            }
            if (data.hasOwnProperty('m_NCP')) {
                obj['m_NCP'] = MNCP.constructFromObject(data['m_NCP']);
            }
            if (data.hasOwnProperty('m_AP')) {
                obj['m_AP'] = MAP.constructFromObject(data['m_AP']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {Boolean} m_AutotuningInProgress
    */
    'm_AutotuningInProgress' = undefined;
    /**
    * @member {Number} m_PercentComplete
    */
    'm_PercentComplete' = undefined;
    /**
    * @member {Boolean} m_AutotuningSucceeded
    */
    'm_AutotuningSucceeded' = undefined;
    /**
    * @member {Number} m_NumPatternsToAutotune
    */
    'm_NumPatternsToAutotune' = undefined;
    /**
    * @member {String} m_ErrorStringBuffer
    */
    'm_ErrorStringBuffer' = undefined;
    /**
    * @member {Array.<Boolean>} m_FeaturesToTuneArray
    */
    'm_FeaturesToTuneArray' = undefined;
    /**
    * @member {module:model/MNCP} m_NCP
    */
    'm_NCP' = undefined;
    /**
    * @member {module:model/MAP} m_AP
    */
    'm_AP' = undefined;




}
