/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MAP} from './MAP';
import {MNCP} from './MNCP';
import {VersionNumber} from './VersionNumber';

/**
 * The MAutotune model module.
 * @module model/MAutotune
 * @version 1.0.3
 */
export class MAutotune {
  /**
   * Constructs a new <code>MAutotune</code>.
   * @alias module:model/MAutotune
   * @class
   * @param mAP {module:model/MAP} 
   */
  constructor(mAP) {
    this.mAP = mAP;
  }

  /**
   * Constructs a <code>MAutotune</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MAutotune} obj Optional instance to populate.
   * @return {module:model/MAutotune} The populated <code>MAutotune</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MAutotune();
      if (data.hasOwnProperty('VersionNumber'))
        obj.versionNumber = VersionNumber.constructFromObject(data['VersionNumber']);
      if (data.hasOwnProperty('m_AutotuningInProgress'))
        obj.mAutotuningInProgress = ApiClient.convertToType(data['m_AutotuningInProgress'], 'Boolean');
      if (data.hasOwnProperty('m_PercentComplete'))
        obj.mPercentComplete = ApiClient.convertToType(data['m_PercentComplete'], 'Number');
      if (data.hasOwnProperty('m_AutotuningSucceeded'))
        obj.mAutotuningSucceeded = ApiClient.convertToType(data['m_AutotuningSucceeded'], 'Boolean');
      if (data.hasOwnProperty('m_NumPatternsToAutotune'))
        obj.mNumPatternsToAutotune = ApiClient.convertToType(data['m_NumPatternsToAutotune'], 'Number');
      if (data.hasOwnProperty('m_ErrorStringBuffer'))
        obj.mErrorStringBuffer = ApiClient.convertToType(data['m_ErrorStringBuffer'], 'String');
      if (data.hasOwnProperty('m_FeaturesToTuneArray'))
        obj.mFeaturesToTuneArray = ApiClient.convertToType(data['m_FeaturesToTuneArray'], ['Boolean']);
      if (data.hasOwnProperty('m_NCP'))
        obj.mNCP = MNCP.constructFromObject(data['m_NCP']);
      if (data.hasOwnProperty('m_AP'))
        obj.mAP = MAP.constructFromObject(data['m_AP']);
    }
    return obj;
  }
}

/**
 * @member {module:model/VersionNumber} versionNumber
 */
MAutotune.prototype.versionNumber = undefined;

/**
 * @member {Boolean} mAutotuningInProgress
 */
MAutotune.prototype.mAutotuningInProgress = undefined;

/**
 * @member {Number} mPercentComplete
 */
MAutotune.prototype.mPercentComplete = undefined;

/**
 * @member {Boolean} mAutotuningSucceeded
 */
MAutotune.prototype.mAutotuningSucceeded = undefined;

/**
 * @member {Number} mNumPatternsToAutotune
 */
MAutotune.prototype.mNumPatternsToAutotune = undefined;

/**
 * @member {String} mErrorStringBuffer
 */
MAutotune.prototype.mErrorStringBuffer = undefined;

/**
 * @member {Array.<Boolean>} mFeaturesToTuneArray
 */
MAutotune.prototype.mFeaturesToTuneArray = undefined;

/**
 * @member {module:model/MNCP} mNCP
 */
MAutotune.prototype.mNCP = undefined;

/**
 * @member {module:model/MAP} mAP
 */
MAutotune.prototype.mAP = undefined;

