/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MPatternMemory from './MPatternMemory';
import VersionNumber from './VersionNumber';

/**
* The MNanoBackend model module.
* @module model/MNanoBackend
* @version 1.0.3
*/
export default class MNanoBackend {
    /**
    * Constructs a new <code>MNanoBackend</code>.
    * @alias module:model/MNanoBackend
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MNanoBackend</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MNanoBackend} obj Optional instance to populate.
    * @return {module:model/MNanoBackend} The populated <code>MNanoBackend</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MNanoBackend();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_PatternMemory')) {
                obj['m_PatternMemory'] = MPatternMemory.constructFromObject(data['m_PatternMemory']);
            }
            if (data.hasOwnProperty('m_InitComplete')) {
                obj['m_InitComplete'] = ApiClient.convertToType(data['m_InitComplete'], 'Boolean');
            }
            if (data.hasOwnProperty('m_PatternLength')) {
                obj['m_PatternLength'] = ApiClient.convertToType(data['m_PatternLength'], 'Number');
            }
            if (data.hasOwnProperty('m_LearningIsOn')) {
                obj['m_LearningIsOn'] = ApiClient.convertToType(data['m_LearningIsOn'], 'Boolean');
            }
            if (data.hasOwnProperty('m_NumOfPatternsClustered')) {
                obj['m_NumOfPatternsClustered'] = ApiClient.convertToType(data['m_NumOfPatternsClustered'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {module:model/MPatternMemory} m_PatternMemory
    */
    'm_PatternMemory' = undefined;
    /**
    * @member {Boolean} m_InitComplete
    */
    'm_InitComplete' = undefined;
    /**
    * @member {Number} m_PatternLength
    */
    'm_PatternLength' = undefined;
    /**
    * @member {Boolean} m_LearningIsOn
    */
    'm_LearningIsOn' = undefined;
    /**
    * @member {Number} m_NumOfPatternsClustered
    */
    'm_NumOfPatternsClustered' = undefined;




}
