/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FeatureConfig from './FeatureConfig';
import VersionNumber from './VersionNumber';

/**
* The MNanoConfig model module.
* @module model/MNanoConfig
* @version 1.0.3
*/
export default class MNanoConfig {
    /**
    * Constructs a new <code>MNanoConfig</code>.
    * @alias module:model/MNanoConfig
    * @class
    * @param mPercentVariation {Number} the percent variation (for instance, 0.025 gives 2.5% variation) used for clustering
    * @param numOfFeatures {Number} 
    * @param features {Array.<module:model/FeatureConfig>} 
    */

    constructor(mPercentVariation, numOfFeatures, features) {
        
        
        this['m_PercentVariation'] = mPercentVariation;
        this['NumOfFeatures'] = numOfFeatures;
        this['Features'] = features;
        
    }

    /**
    * Constructs a <code>MNanoConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MNanoConfig} obj Optional instance to populate.
    * @return {module:model/MNanoConfig} The populated <code>MNanoConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MNanoConfig();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_NumericFormat')) {
                obj['m_NumericFormat'] = ApiClient.convertToType(data['m_NumericFormat'], 'Number');
            }
            if (data.hasOwnProperty('m_Accuracy')) {
                obj['m_Accuracy'] = ApiClient.convertToType(data['m_Accuracy'], 'Number');
            }
            if (data.hasOwnProperty('m_PercentVariation')) {
                obj['m_PercentVariation'] = ApiClient.convertToType(data['m_PercentVariation'], 'Number');
            }
            if (data.hasOwnProperty('NumOfFeatures')) {
                obj['NumOfFeatures'] = ApiClient.convertToType(data['NumOfFeatures'], 'Number');
            }
            if (data.hasOwnProperty('Features')) {
                obj['Features'] = ApiClient.convertToType(data['Features'], [FeatureConfig]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {Number} m_NumericFormat
    */
    'm_NumericFormat' = undefined;
    /**
    * @member {Number} m_Accuracy
    */
    'm_Accuracy' = undefined;
    /**
    * the percent variation (for instance, 0.025 gives 2.5% variation) used for clustering
    * @member {Number} m_PercentVariation
    */
    'm_PercentVariation' = undefined;
    /**
    * @member {Number} NumOfFeatures
    */
    'NumOfFeatures' = undefined;
    /**
    * @member {Array.<module:model/FeatureConfig>} Features
    */
    'Features' = undefined;




}
