/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VersionNumber from './VersionNumber';

/**
* The MNCP model module.
* @module model/MNCP
* @version 1.0.3
*/
export default class MNCP {
    /**
    * Constructs a new <code>MNCP</code>.
    * @alias module:model/MNCP
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MNCP</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MNCP} obj Optional instance to populate.
    * @return {module:model/MNCP} The populated <code>MNCP</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MNCP();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('NumOfFeatures')) {
                obj['NumOfFeatures'] = ApiClient.convertToType(data['NumOfFeatures'], 'Number');
            }
            if (data.hasOwnProperty('m_NumericFormat')) {
                obj['m_NumericFormat'] = ApiClient.convertToType(data['m_NumericFormat'], 'Number');
            }
            if (data.hasOwnProperty('m_PercentVariation')) {
                obj['m_PercentVariation'] = ApiClient.convertToType(data['m_PercentVariation'], 'Number');
            }
            if (data.hasOwnProperty('m_Accuracy')) {
                obj['m_Accuracy'] = ApiClient.convertToType(data['m_Accuracy'], 'Number');
            }
            if (data.hasOwnProperty('m_StreamingWindowSize')) {
                obj['m_StreamingWindowSize'] = ApiClient.convertToType(data['m_StreamingWindowSize'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {Number} NumOfFeatures
    */
    'NumOfFeatures' = undefined;
    /**
    * @member {Number} m_NumericFormat
    */
    'm_NumericFormat' = undefined;
    /**
    * @member {Number} m_PercentVariation
    */
    'm_PercentVariation' = undefined;
    /**
    * @member {Number} m_Accuracy
    */
    'm_Accuracy' = undefined;
    /**
    * @member {Number} m_StreamingWindowSize
    */
    'm_StreamingWindowSize' = undefined;




}
