/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VersionNumber} from './VersionNumber';

/**
 * The MRecentTimes model module.
 * @module model/MRecentTimes
 * @version 1.0.3
 */
export class MRecentTimes {
  /**
   * Constructs a new <code>MRecentTimes</code>.
   * @alias module:model/MRecentTimes
   * @class
   * @param mValues {Array.<Number>} 
   */
  constructor(mValues) {
    this.mValues = mValues;
  }

  /**
   * Constructs a <code>MRecentTimes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MRecentTimes} obj Optional instance to populate.
   * @return {module:model/MRecentTimes} The populated <code>MRecentTimes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MRecentTimes();
      if (data.hasOwnProperty('VersionNumber'))
        obj.versionNumber = VersionNumber.constructFromObject(data['VersionNumber']);
      if (data.hasOwnProperty('m_Values'))
        obj.mValues = ApiClient.convertToType(data['m_Values'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {module:model/VersionNumber} versionNumber
 */
MRecentTimes.prototype.versionNumber = undefined;

/**
 * @member {Array.<Number>} mValues
 */
MRecentTimes.prototype.mValues = undefined;

