/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VersionNumber from './VersionNumber';

/**
* The MRecentSamples model module.
* @module model/MRecentSamples
* @version 1.0.3
*/
export default class MRecentSamples {
    /**
    * Constructs a new <code>MRecentSamples</code>.
    * @alias module:model/MRecentSamples
    * @class
    * @param mValues {Array.<Array.<Number>>} 
    */

    constructor(mValues) {
        
        
        this['m_Values'] = mValues;
        
    }

    /**
    * Constructs a <code>MRecentSamples</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MRecentSamples} obj Optional instance to populate.
    * @return {module:model/MRecentSamples} The populated <code>MRecentSamples</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MRecentSamples();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_Values')) {
                obj['m_Values'] = ApiClient.convertToType(data['m_Values'], [['Number']]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {Array.<Array.<Number>>} m_Values
    */
    'm_Values' = undefined;




}
