/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VersionNumber} from './VersionNumber';

/**
 * The MStreamingParameters model module.
 * @module model/MStreamingParameters
 * @version 1.0.3
 */
export class MStreamingParameters {
  /**
   * Constructs a new <code>MStreamingParameters</code>.
   * @alias module:model/MStreamingParameters
   * @class
   * @param mSamplesToBufferForAutotuning {Number} 
   * @param mGraduationAtRateNumerator {Number} 
   * @param mGraduationAtRateDenominator {Number} 
   * @param mGraduateAtMaxClusters {Number} 
   * @param mGraduateAtMaxSamples {Number} 
   */
  constructor(mSamplesToBufferForAutotuning, mGraduationAtRateNumerator, mGraduationAtRateDenominator, mGraduateAtMaxClusters, mGraduateAtMaxSamples) {
    this.mSamplesToBufferForAutotuning = mSamplesToBufferForAutotuning;
    this.mGraduationAtRateNumerator = mGraduationAtRateNumerator;
    this.mGraduationAtRateDenominator = mGraduationAtRateDenominator;
    this.mGraduateAtMaxClusters = mGraduateAtMaxClusters;
    this.mGraduateAtMaxSamples = mGraduateAtMaxSamples;
  }

  /**
   * Constructs a <code>MStreamingParameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MStreamingParameters} obj Optional instance to populate.
   * @return {module:model/MStreamingParameters} The populated <code>MStreamingParameters</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MStreamingParameters();
      if (data.hasOwnProperty('VersionNumber'))
        obj.versionNumber = VersionNumber.constructFromObject(data['VersionNumber']);
      if (data.hasOwnProperty('m_EnableAutotuning'))
        obj.mEnableAutotuning = ApiClient.convertToType(data['m_EnableAutotuning'], 'Boolean');
      if (data.hasOwnProperty('m_SamplesToBufferForAutotuning'))
        obj.mSamplesToBufferForAutotuning = ApiClient.convertToType(data['m_SamplesToBufferForAutotuning'], 'Number');
      if (data.hasOwnProperty('m_GraduationAtRateNumerator'))
        obj.mGraduationAtRateNumerator = ApiClient.convertToType(data['m_GraduationAtRateNumerator'], 'Number');
      if (data.hasOwnProperty('m_GraduationAtRateDenominator'))
        obj.mGraduationAtRateDenominator = ApiClient.convertToType(data['m_GraduationAtRateDenominator'], 'Number');
      if (data.hasOwnProperty('m_GraduateAtMaxClusters'))
        obj.mGraduateAtMaxClusters = ApiClient.convertToType(data['m_GraduateAtMaxClusters'], 'Number');
      if (data.hasOwnProperty('m_GraduateAtMaxSamples'))
        obj.mGraduateAtMaxSamples = ApiClient.convertToType(data['m_GraduateAtMaxSamples'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/VersionNumber} versionNumber
 */
MStreamingParameters.prototype.versionNumber = undefined;

/**
 * @member {Boolean} mEnableAutotuning
 */
MStreamingParameters.prototype.mEnableAutotuning = undefined;

/**
 * @member {Number} mSamplesToBufferForAutotuning
 */
MStreamingParameters.prototype.mSamplesToBufferForAutotuning = undefined;

/**
 * @member {Number} mGraduationAtRateNumerator
 */
MStreamingParameters.prototype.mGraduationAtRateNumerator = undefined;

/**
 * @member {Number} mGraduationAtRateDenominator
 */
MStreamingParameters.prototype.mGraduationAtRateDenominator = undefined;

/**
 * @member {Number} mGraduateAtMaxClusters
 */
MStreamingParameters.prototype.mGraduateAtMaxClusters = undefined;

/**
 * @member {Number} mGraduateAtMaxSamples
 */
MStreamingParameters.prototype.mGraduateAtMaxSamples = undefined;

