/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VersionNumber from './VersionNumber';

/**
* The MStreamingParameters model module.
* @module model/MStreamingParameters
* @version 1.0.3
*/
export default class MStreamingParameters {
    /**
    * Constructs a new <code>MStreamingParameters</code>.
    * @alias module:model/MStreamingParameters
    * @class
    * @param mSamplesToBufferForAutotuning {Number} 
    * @param mGraduationAtRateNumerator {Number} 
    * @param mGraduationAtRateDenominator {Number} 
    * @param mGraduateAtMaxClusters {Number} 
    * @param mGraduateAtMaxSamples {Number} 
    */

    constructor(mSamplesToBufferForAutotuning, mGraduationAtRateNumerator, mGraduationAtRateDenominator, mGraduateAtMaxClusters, mGraduateAtMaxSamples) {
        
        
        this['m_SamplesToBufferForAutotuning'] = mSamplesToBufferForAutotuning;
        this['m_GraduationAtRateNumerator'] = mGraduationAtRateNumerator;
        this['m_GraduationAtRateDenominator'] = mGraduationAtRateDenominator;
        this['m_GraduateAtMaxClusters'] = mGraduateAtMaxClusters;
        this['m_GraduateAtMaxSamples'] = mGraduateAtMaxSamples;
        
    }

    /**
    * Constructs a <code>MStreamingParameters</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MStreamingParameters} obj Optional instance to populate.
    * @return {module:model/MStreamingParameters} The populated <code>MStreamingParameters</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MStreamingParameters();
                        
            
            if (data.hasOwnProperty('VersionNumber')) {
                obj['VersionNumber'] = VersionNumber.constructFromObject(data['VersionNumber']);
            }
            if (data.hasOwnProperty('m_EnableAutotuning')) {
                obj['m_EnableAutotuning'] = ApiClient.convertToType(data['m_EnableAutotuning'], 'Boolean');
            }
            if (data.hasOwnProperty('m_SamplesToBufferForAutotuning')) {
                obj['m_SamplesToBufferForAutotuning'] = ApiClient.convertToType(data['m_SamplesToBufferForAutotuning'], 'Number');
            }
            if (data.hasOwnProperty('m_GraduationAtRateNumerator')) {
                obj['m_GraduationAtRateNumerator'] = ApiClient.convertToType(data['m_GraduationAtRateNumerator'], 'Number');
            }
            if (data.hasOwnProperty('m_GraduationAtRateDenominator')) {
                obj['m_GraduationAtRateDenominator'] = ApiClient.convertToType(data['m_GraduationAtRateDenominator'], 'Number');
            }
            if (data.hasOwnProperty('m_GraduateAtMaxClusters')) {
                obj['m_GraduateAtMaxClusters'] = ApiClient.convertToType(data['m_GraduateAtMaxClusters'], 'Number');
            }
            if (data.hasOwnProperty('m_GraduateAtMaxSamples')) {
                obj['m_GraduateAtMaxSamples'] = ApiClient.convertToType(data['m_GraduateAtMaxSamples'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VersionNumber} VersionNumber
    */
    'VersionNumber' = undefined;
    /**
    * @member {Boolean} m_EnableAutotuning
    */
    'm_EnableAutotuning' = undefined;
    /**
    * @member {Number} m_SamplesToBufferForAutotuning
    */
    'm_SamplesToBufferForAutotuning' = undefined;
    /**
    * @member {Number} m_GraduationAtRateNumerator
    */
    'm_GraduationAtRateNumerator' = undefined;
    /**
    * @member {Number} m_GraduationAtRateDenominator
    */
    'm_GraduationAtRateDenominator' = undefined;
    /**
    * @member {Number} m_GraduateAtMaxClusters
    */
    'm_GraduateAtMaxClusters' = undefined;
    /**
    * @member {Number} m_GraduateAtMaxSamples
    */
    'm_GraduateAtMaxSamples' = undefined;




}
