/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VersionNumber} from './VersionNumber';

/**
 * The MTraining model module.
 * @module model/MTraining
 * @version 1.0.3
 */
export class MTraining {
  /**
   * Constructs a new <code>MTraining</code>.
   * @alias module:model/MTraining
   * @class
   * @param mGeometricPlotY {Array.<Number>} 
   * @param mGeometricPlotX {Array.<Number>} 
   * @param mClusterGrowth {Array.<Number>} 
   */
  constructor(mGeometricPlotY, mGeometricPlotX, mClusterGrowth) {
    this.mGeometricPlotY = mGeometricPlotY;
    this.mGeometricPlotX = mGeometricPlotX;
    this.mClusterGrowth = mClusterGrowth;
  }

  /**
   * Constructs a <code>MTraining</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MTraining} obj Optional instance to populate.
   * @return {module:model/MTraining} The populated <code>MTraining</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MTraining();
      if (data.hasOwnProperty('VersionNumber'))
        obj.versionNumber = ApiClient.convertToType(data['VersionNumber'], [VersionNumber]);
      if (data.hasOwnProperty('m_GeometricPlotY'))
        obj.mGeometricPlotY = ApiClient.convertToType(data['m_GeometricPlotY'], ['Number']);
      if (data.hasOwnProperty('m_GeometricPlotX'))
        obj.mGeometricPlotX = ApiClient.convertToType(data['m_GeometricPlotX'], ['Number']);
      if (data.hasOwnProperty('m_ClusterGrowth'))
        obj.mClusterGrowth = ApiClient.convertToType(data['m_ClusterGrowth'], ['Number']);
      if (data.hasOwnProperty('m_AnomalyIndexes'))
        obj.mAnomalyIndexes = ApiClient.convertToType(data['m_AnomalyIndexes'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/VersionNumber>} versionNumber
 */
MTraining.prototype.versionNumber = undefined;

/**
 * @member {Array.<Number>} mGeometricPlotY
 */
MTraining.prototype.mGeometricPlotY = undefined;

/**
 * @member {Array.<Number>} mGeometricPlotX
 */
MTraining.prototype.mGeometricPlotX = undefined;

/**
 * @member {Array.<Number>} mClusterGrowth
 */
MTraining.prototype.mClusterGrowth = undefined;

/**
 * @member {Array.<Number>} mAnomalyIndexes
 */
MTraining.prototype.mAnomalyIndexes = undefined;

