/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {FeatureConfig} from './FeatureConfig';
import {StreamingParameters} from './StreamingParameters';

/**
 * The PostConfigResponse model module.
 * @module model/PostConfigResponse
 * @version 1.0.3
 */
export class PostConfigResponse extends StreamingParameters {
  /**
   * Constructs a new <code>PostConfigResponse</code>.
   * @alias module:model/PostConfigResponse
   * @class
   * @extends module:model/StreamingParameters
   * @param featureCount {} number of features per sample
   * @param streamingWindowSize {} streaming window size
   * @param samplesToBuffer {} the number of samples to be applied before autotuning begins
   */
  constructor(featureCount, streamingWindowSize, samplesToBuffer) {
    super();
    this.featureCount = featureCount;
    this.streamingWindowSize = streamingWindowSize;
    this.samplesToBuffer = samplesToBuffer;
  }

  /**
   * Constructs a <code>PostConfigResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostConfigResponse} obj Optional instance to populate.
   * @return {module:model/PostConfigResponse} The populated <code>PostConfigResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostConfigResponse();
      StreamingParameters.constructFromObject(data, obj);
      if (data.hasOwnProperty('featureCount'))
        obj.featureCount = ApiClient.convertToType(data['featureCount'], 'Number');
      if (data.hasOwnProperty('streamingWindowSize'))
        obj.streamingWindowSize = ApiClient.convertToType(data['streamingWindowSize'], 'Number');
      if (data.hasOwnProperty('features'))
        obj.features = ApiClient.convertToType(data['features'], [FeatureConfig]);
      if (data.hasOwnProperty('samplesToBuffer'))
        obj.samplesToBuffer = ApiClient.convertToType(data['samplesToBuffer'], 'Number');
    }
    return obj;
  }
}

/**
 * number of features per sample
 * @member {Number} featureCount
 */
PostConfigResponse.prototype.featureCount = undefined;

/**
 * streaming window size
 * @member {Number} streamingWindowSize
 */
PostConfigResponse.prototype.streamingWindowSize = undefined;

/**
 * @member {Array.<module:model/FeatureConfig>} features
 */
PostConfigResponse.prototype.features = undefined;

/**
 * the number of samples to be applied before autotuning begins
 * @member {Number} samplesToBuffer
 */
PostConfigResponse.prototype.samplesToBuffer = undefined;

