/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostConfigRequest from './PostConfigRequest';

/**
* The PostConfigResponse model module.
* @module model/PostConfigResponse
* @version 1.0.3
*/
export default class PostConfigResponse {
    /**
    * Constructs a new <code>PostConfigResponse</code>.
    * @alias module:model/PostConfigResponse
    * @class
    * @extends module:model/PostConfigRequest
    * @param featureCount {} number of features per sample
    * @param streamingWindowSize {} streaming window size
    */

    constructor(featureCount, streamingWindowSize) {
        PostConfigRequest.call(this, featureCount, streamingWindowSize);
        
        
    }

    /**
    * Constructs a <code>PostConfigResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PostConfigResponse} obj Optional instance to populate.
    * @return {module:model/PostConfigResponse} The populated <code>PostConfigResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostConfigResponse();
            
            PostConfigRequest.constructFromObject(data, obj);
            
        }
        return obj;
    }





}
