/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SensorInstance} from './SensorInstance';

/**
 * The PostSensorResponse model module.
 * @module model/PostSensorResponse
 * @version 1.0.3
 */
export class PostSensorResponse extends SensorInstance {
  /**
   * Constructs a new <code>PostSensorResponse</code>.
   * @alias module:model/PostSensorResponse
   * @class
   * @extends module:model/SensorInstance
   * @param label {} Additional label to be assigned for sensor
   * @param sensorId {} Unique identifier for sensor
   */
  constructor(label, sensorId) {
    super(label, sensorId);
  }

  /**
   * Constructs a <code>PostSensorResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostSensorResponse} obj Optional instance to populate.
   * @return {module:model/PostSensorResponse} The populated <code>PostSensorResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostSensorResponse();
      SensorInstance.constructFromObject(data, obj);
    }
    return obj;
  }
}
