/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {FusionConfig} from './FusionConfig';

/**
 * The PutConfigRequest model module.
 * @module model/PutConfigRequest
 * @version 1.0.3
 */
export class PutConfigRequest {
  /**
   * Constructs a new <code>PutConfigRequest</code>.
   * @alias module:model/PutConfigRequest
   * @class
   * @param features {Array.<module:model/FusionConfig>} 
   */
  constructor(features) {
    this.features = features;
  }

  /**
   * Constructs a <code>PutConfigRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutConfigRequest} obj Optional instance to populate.
   * @return {module:model/PutConfigRequest} The populated <code>PutConfigRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutConfigRequest();
      if (data.hasOwnProperty('features'))
        obj.features = ApiClient.convertToType(data['features'], [FusionConfig]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/FusionConfig>} features
 */
PutConfigRequest.prototype.features = undefined;

