/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PutStreamFeature model module.
 * @module model/PutStreamFeature
 * @version 1.0.3
 */
export class PutStreamFeature {
  /**
   * Constructs a new <code>PutStreamFeature</code>.
   * @alias module:model/PutStreamFeature
   * @class
   * @param label {String} label associated with feature
   * @param value {Number} new value for this feature in sensor fusion vector
   */
  constructor(label, value) {
    this.label = label;
    this.value = value;
  }

  /**
   * Constructs a <code>PutStreamFeature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutStreamFeature} obj Optional instance to populate.
   * @return {module:model/PutStreamFeature} The populated <code>PutStreamFeature</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutStreamFeature();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('ts'))
        obj.ts = ApiClient.convertToType(data['ts'], 'String');
    }
    return obj;
  }
}

/**
 * label associated with feature
 * @member {String} label
 */
PutStreamFeature.prototype.label = undefined;

/**
 * new value for this feature in sensor fusion vector
 * @member {Number} value
 */
PutStreamFeature.prototype.value = undefined;

/**
 * ISO-format timestamp for this data value
 * @member {String} ts
 */
PutStreamFeature.prototype.ts = undefined;

