/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PostStreamResponse} from './PostStreamResponse';

/**
 * The PutStreamResponse model module.
 * @module model/PutStreamResponse
 * @version 1.0.3
 */
export class PutStreamResponse {
  /**
   * Constructs a new <code>PutStreamResponse</code>.
   * @alias module:model/PutStreamResponse
   * @class
   * @param vector {String} updated sensor fusion vector as a string of comma-separated values
   */
  constructor(vector) {
    this.vector = vector;
  }

  /**
   * Constructs a <code>PutStreamResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutStreamResponse} obj Optional instance to populate.
   * @return {module:model/PutStreamResponse} The populated <code>PutStreamResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutStreamResponse();
      if (data.hasOwnProperty('vector'))
        obj.vector = ApiClient.convertToType(data['vector'], 'String');
      if (data.hasOwnProperty('results'))
        obj.results = PostStreamResponse.constructFromObject(data['results']);
    }
    return obj;
  }
}

/**
 * updated sensor fusion vector as a string of comma-separated values
 * @member {String} vector
 */
PutStreamResponse.prototype.vector = undefined;

/**
 * @member {module:model/PostStreamResponse} results
 */
PutStreamResponse.prototype.results = undefined;

