/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PutSensorResponse model module.
 * @module model/PutSensorResponse
 * @version 1.0.3
 */
export class PutSensorResponse {
  /**
   * Constructs a new <code>PutSensorResponse</code>.
   * @alias module:model/PutSensorResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PutSensorResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutSensorResponse} obj Optional instance to populate.
   * @return {module:model/PutSensorResponse} The populated <code>PutSensorResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutSensorResponse();
    }
    return obj;
  }
}
