/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SensorInstance model module.
* @module model/SensorInstance
* @version 1.0.3
*/
export default class SensorInstance {
    /**
    * Constructs a new <code>SensorInstance</code>.
    * @alias module:model/SensorInstance
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SensorInstance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SensorInstance} obj Optional instance to populate.
    * @return {module:model/SensorInstance} The populated <code>SensorInstance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SensorInstance();
                        
            
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('sensorId')) {
                obj['sensorId'] = ApiClient.convertToType(data['sensorId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Additional label to be assigned for sensor
    * @member {String} label
    */
    'label' = undefined;
    /**
    * Unique identifier for sensor
    * @member {String} sensorId
    */
    'sensorId' = undefined;




}
