/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SensorInstance model module.
 * @module model/SensorInstance
 * @version 1.0.3
 */
export class SensorInstance {
  /**
   * Constructs a new <code>SensorInstance</code>.
   * @alias module:model/SensorInstance
   * @class
   * @param label {String} Additional label to be assigned for sensor
   * @param sensorId {String} Unique identifier for sensor
   */
  constructor(label, sensorId) {
    this.label = label;
    this.sensorId = sensorId;
  }

  /**
   * Constructs a <code>SensorInstance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SensorInstance} obj Optional instance to populate.
   * @return {module:model/SensorInstance} The populated <code>SensorInstance</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SensorInstance();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('sensorId'))
        obj.sensorId = ApiClient.convertToType(data['sensorId'], 'String');
    }
    return obj;
  }
}

/**
 * Additional label to be assigned for sensor
 * @member {String} label
 */
SensorInstance.prototype.label = undefined;

/**
 * Unique identifier for sensor
 * @member {String} sensorId
 */
SensorInstance.prototype.sensorId = undefined;

