/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The StreamingEndpointUsageInfo model module.
 * @module model/StreamingEndpointUsageInfo
 * @version 1.0.3
 */
export class StreamingEndpointUsageInfo {
  /**
   * Constructs a new <code>StreamingEndpointUsageInfo</code>.
   * @alias module:model/StreamingEndpointUsageInfo
   * @class
   * @param callsTotal {Number} total number of calls to this endpoint
   * @param callsThisPeriod {Number} number of calls to this endpoint during the current billing period
   * @param samplesTotal {Number} total number of samples processed
   * @param samplesThisPeriod {Number} number of samples processed during the current billing period
   * @param lastCalled {String} ISO formatted time of last call to this endpoint
   */
  constructor(callsTotal, callsThisPeriod, samplesTotal, samplesThisPeriod, lastCalled) {
    this.callsTotal = callsTotal;
    this.callsThisPeriod = callsThisPeriod;
    this.samplesTotal = samplesTotal;
    this.samplesThisPeriod = samplesThisPeriod;
    this.lastCalled = lastCalled;
  }

  /**
   * Constructs a <code>StreamingEndpointUsageInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamingEndpointUsageInfo} obj Optional instance to populate.
   * @return {module:model/StreamingEndpointUsageInfo} The populated <code>StreamingEndpointUsageInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamingEndpointUsageInfo();
      if (data.hasOwnProperty('callsTotal'))
        obj.callsTotal = ApiClient.convertToType(data['callsTotal'], 'Number');
      if (data.hasOwnProperty('callsThisPeriod'))
        obj.callsThisPeriod = ApiClient.convertToType(data['callsThisPeriod'], 'Number');
      if (data.hasOwnProperty('samplesTotal'))
        obj.samplesTotal = ApiClient.convertToType(data['samplesTotal'], 'Number');
      if (data.hasOwnProperty('samplesThisPeriod'))
        obj.samplesThisPeriod = ApiClient.convertToType(data['samplesThisPeriod'], 'Number');
      if (data.hasOwnProperty('lastCalled'))
        obj.lastCalled = ApiClient.convertToType(data['lastCalled'], 'String');
    }
    return obj;
  }
}

/**
 * total number of calls to this endpoint
 * @member {Number} callsTotal
 */
StreamingEndpointUsageInfo.prototype.callsTotal = undefined;

/**
 * number of calls to this endpoint during the current billing period
 * @member {Number} callsThisPeriod
 */
StreamingEndpointUsageInfo.prototype.callsThisPeriod = undefined;

/**
 * total number of samples processed
 * @member {Number} samplesTotal
 */
StreamingEndpointUsageInfo.prototype.samplesTotal = undefined;

/**
 * number of samples processed during the current billing period
 * @member {Number} samplesThisPeriod
 */
StreamingEndpointUsageInfo.prototype.samplesThisPeriod = undefined;

/**
 * ISO formatted time of last call to this endpoint
 * @member {String} lastCalled
 */
StreamingEndpointUsageInfo.prototype.lastCalled = undefined;

