/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TotalInferences model module.
* @module model/TotalInferences
* @version 1.0.3
*/
export default class TotalInferences {
    /**
    * Constructs a new <code>TotalInferences</code>.
    * @alias module:model/TotalInferences
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TotalInferences</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TotalInferences} obj Optional instance to populate.
    * @return {module:model/TotalInferences} The populated <code>TotalInferences</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TotalInferences();
                        
            
        }
        return obj;
    }





}
