/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Uint32Array model module.
* @module model/Uint32Array
* @version 1.0.3
*/
export default class Uint32Array extends Array {
    /**
    * Constructs a new <code>Uint32Array</code>.
    * @alias module:model/Uint32Array
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>Uint32Array</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Uint32Array} obj Optional instance to populate.
    * @return {module:model/Uint32Array} The populated <code>Uint32Array</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Uint32Array();
            ApiClient.constructFromObject(data, obj, 'Number');
            
            
        }
        return obj;
    }





}
