/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Version model module.
 * @module model/Version
 * @version 1.0.3
 */
export class Version {
  /**
   * Constructs a new <code>Version</code>.
   * @alias module:model/Version
   * @class
   * @param release {String} 
   * @param apiVersion {String} 
   * @param builder {String} 
   * @param expertApi {String} 
   * @param expertCommon {String} 
   * @param nanoSecure {String} 
   * @param swaggerUi {String} 
   */
  constructor(release, apiVersion, builder, expertApi, expertCommon, nanoSecure, swaggerUi) {
    this.release = release;
    this.apiVersion = apiVersion;
    this.builder = builder;
    this.expertApi = expertApi;
    this.expertCommon = expertCommon;
    this.nanoSecure = nanoSecure;
    this.swaggerUi = swaggerUi;
  }

  /**
   * Constructs a <code>Version</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Version} obj Optional instance to populate.
   * @return {module:model/Version} The populated <code>Version</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Version();
      if (data.hasOwnProperty('release'))
        obj.release = ApiClient.convertToType(data['release'], 'String');
      if (data.hasOwnProperty('api-version'))
        obj.apiVersion = ApiClient.convertToType(data['api-version'], 'String');
      if (data.hasOwnProperty('builder'))
        obj.builder = ApiClient.convertToType(data['builder'], 'String');
      if (data.hasOwnProperty('expert-api'))
        obj.expertApi = ApiClient.convertToType(data['expert-api'], 'String');
      if (data.hasOwnProperty('expert-common'))
        obj.expertCommon = ApiClient.convertToType(data['expert-common'], 'String');
      if (data.hasOwnProperty('nano-secure'))
        obj.nanoSecure = ApiClient.convertToType(data['nano-secure'], 'String');
      if (data.hasOwnProperty('swagger-ui'))
        obj.swaggerUi = ApiClient.convertToType(data['swagger-ui'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} release
 */
Version.prototype.release = undefined;

/**
 * @member {String} apiVersion
 */
Version.prototype.apiVersion = undefined;

/**
 * @member {String} builder
 */
Version.prototype.builder = undefined;

/**
 * @member {String} expertApi
 */
Version.prototype.expertApi = undefined;

/**
 * @member {String} expertCommon
 */
Version.prototype.expertCommon = undefined;

/**
 * @member {String} nanoSecure
 */
Version.prototype.nanoSecure = undefined;

/**
 * @member {String} swaggerUi
 */
Version.prototype.swaggerUi = undefined;

