/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Version model module.
* @module model/Version
* @version 1.0.3
*/
export default class Version {
    /**
    * Constructs a new <code>Version</code>.
    * @alias module:model/Version
    * @class
    * @param release {String} 
    * @param apiVersion {String} 
    * @param builder {String} 
    * @param expertApi {String} 
    * @param expertCommon {String} 
    * @param nanoSecure {String} 
    * @param swaggerUi {String} 
    */

    constructor(release, apiVersion, builder, expertApi, expertCommon, nanoSecure, swaggerUi) {
        
        
        this['release'] = release;
        this['api-version'] = apiVersion;
        this['builder'] = builder;
        this['expert-api'] = expertApi;
        this['expert-common'] = expertCommon;
        this['nano-secure'] = nanoSecure;
        this['swagger-ui'] = swaggerUi;
        
    }

    /**
    * Constructs a <code>Version</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Version} obj Optional instance to populate.
    * @return {module:model/Version} The populated <code>Version</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Version();
                        
            
            if (data.hasOwnProperty('release')) {
                obj['release'] = ApiClient.convertToType(data['release'], 'String');
            }
            if (data.hasOwnProperty('api-version')) {
                obj['api-version'] = ApiClient.convertToType(data['api-version'], 'String');
            }
            if (data.hasOwnProperty('builder')) {
                obj['builder'] = ApiClient.convertToType(data['builder'], 'String');
            }
            if (data.hasOwnProperty('expert-api')) {
                obj['expert-api'] = ApiClient.convertToType(data['expert-api'], 'String');
            }
            if (data.hasOwnProperty('expert-common')) {
                obj['expert-common'] = ApiClient.convertToType(data['expert-common'], 'String');
            }
            if (data.hasOwnProperty('nano-secure')) {
                obj['nano-secure'] = ApiClient.convertToType(data['nano-secure'], 'String');
            }
            if (data.hasOwnProperty('swagger-ui')) {
                obj['swagger-ui'] = ApiClient.convertToType(data['swagger-ui'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} release
    */
    'release' = undefined;
    /**
    * @member {String} api-version
    */
    'api-version' = undefined;
    /**
    * @member {String} builder
    */
    'builder' = undefined;
    /**
    * @member {String} expert-api
    */
    'expert-api' = undefined;
    /**
    * @member {String} expert-common
    */
    'expert-common' = undefined;
    /**
    * @member {String} nano-secure
    */
    'nano-secure' = undefined;
    /**
    * @member {String} swagger-ui
    */
    'swagger-ui' = undefined;




}
