/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetSensorResponse', function() {
      beforeEach(function() {
        instance = new AmberApiServer.GetSensorResponse();
      });

      it('should create an instance of GetSensorResponse', function() {
        // TODO: update the code to test GetSensorResponse
        expect(instance).to.be.a(AmberApiServer.GetSensorResponse);
      });

      it('should have the property label (base name: "label")', function() {
        // TODO: update the code to test the property label
        expect(instance).to.have.property('label');
        // expect(instance.label).to.be(expectedValueLiteral);
      });

      it('should have the property sensorId (base name: "sensorId")', function() {
        // TODO: update the code to test the property sensorId
        expect(instance).to.have.property('sensorId');
        // expect(instance.sensorId).to.be(expectedValueLiteral);
      });

      it('should have the property usageInfo (base name: "usageInfo")', function() {
        // TODO: update the code to test the property usageInfo
        expect(instance).to.have.property('usageInfo');
        // expect(instance.usageInfo).to.be(expectedValueLiteral);
      });

    });
  });

}));
