/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmberApiServer.MAmberStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MAmberStatus', function() {
    it('should create an instance of MAmberStatus', function() {
      // uncomment below and update the code to test MAmberStatus
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be.a(AmberApiServer.MAmberStatus);
    });

    it('should have the property versionNumber (base name: "VersionNumber")', function() {
      // uncomment below and update the code to test the property versionNumber
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mStatus (base name: "m_Status")', function() {
      // uncomment below and update the code to test the property mStatus
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mMessage (base name: "m_Message")', function() {
      // uncomment below and update the code to test the property mMessage
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mProgress (base name: "m_Progress")', function() {
      // uncomment below and update the code to test the property mProgress
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mCurrentClusterCount (base name: "m_CurrentClusterCount")', function() {
      // uncomment below and update the code to test the property mCurrentClusterCount
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mRetryCount (base name: "m_RetryCount")', function() {
      // uncomment below and update the code to test the property mRetryCount
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mStreamingWindowSize (base name: "m_StreamingWindowSize")', function() {
      // uncomment below and update the code to test the property mStreamingWindowSize
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mTotalInferences (base name: "m_TotalInferences")', function() {
      // uncomment below and update the code to test the property mTotalInferences
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

    it('should have the property mTotalSamplesWritten (base name: "m_TotalSamplesWritten")', function() {
      // uncomment below and update the code to test the property mTotalSamplesWritten
      //var instane = new AmberApiServer.MAmberStatus();
      //expect(instance).to.be();
    });

  });

}));
