/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmberApiServer.MAP();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MAP', function() {
    it('should create an instance of MAP', function() {
      // uncomment below and update the code to test MAP
      //var instane = new AmberApiServer.MAP();
      //expect(instance).to.be.a(AmberApiServer.MAP);
    });

    it('should have the property versionNumber (base name: "VersionNumber")', function() {
      // uncomment below and update the code to test the property versionNumber
      //var instane = new AmberApiServer.MAP();
      //expect(instance).to.be();
    });

    it('should have the property mAutotuneRange (base name: "m_AutotuneRange")', function() {
      // uncomment below and update the code to test the property mAutotuneRange
      //var instane = new AmberApiServer.MAP();
      //expect(instance).to.be();
    });

    it('should have the property mAutotunePV (base name: "m_AutotunePV")', function() {
      // uncomment below and update the code to test the property mAutotunePV
      //var instane = new AmberApiServer.MAP();
      //expect(instance).to.be();
    });

    it('should have the property mAutotuneByFeatures (base name: "m_AutotuneByFeatures")', function() {
      // uncomment below and update the code to test the property mAutotuneByFeatures
      //var instane = new AmberApiServer.MAP();
      //expect(instance).to.be();
    });

    it('should have the property mMaxClusters (base name: "m_MaxClusters")', function() {
      // uncomment below and update the code to test the property mMaxClusters
      //var instane = new AmberApiServer.MAP();
      //expect(instance).to.be();
    });

    it('should have the property mFeaturesToTuneArray (base name: "m_FeaturesToTuneArray")', function() {
      // uncomment below and update the code to test the property mFeaturesToTuneArray
      //var instane = new AmberApiServer.MAP();
      //expect(instance).to.be();
    });

  });

}));
