/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmberApiServer.MNano();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MNano', function() {
    it('should create an instance of MNano', function() {
      // uncomment below and update the code to test MNano
      //var instane = new AmberApiServer.MNano();
      //expect(instance).to.be.a(AmberApiServer.MNano);
    });

    it('should have the property mNanoConfig (base name: "m_NanoConfig")', function() {
      // uncomment below and update the code to test the property mNanoConfig
      //var instane = new AmberApiServer.MNano();
      //expect(instance).to.be();
    });

    it('should have the property magicNumber (base name: "MagicNumber")', function() {
      // uncomment below and update the code to test the property magicNumber
      //var instane = new AmberApiServer.MNano();
      //expect(instance).to.be();
    });

    it('should have the property versionNumber (base name: "VersionNumber")', function() {
      // uncomment below and update the code to test the property versionNumber
      //var instane = new AmberApiServer.MNano();
      //expect(instance).to.be();
    });

    it('should have the property backendVersion (base name: "BackendVersion")', function() {
      // uncomment below and update the code to test the property backendVersion
      //var instane = new AmberApiServer.MNano();
      //expect(instance).to.be();
    });

    it('should have the property mErrorMsg (base name: "m_ErrorMsg")', function() {
      // uncomment below and update the code to test the property mErrorMsg
      //var instane = new AmberApiServer.MNano();
      //expect(instance).to.be();
    });

    it('should have the property mNanoBackend (base name: "m_NanoBackend")', function() {
      // uncomment below and update the code to test the property mNanoBackend
      //var instane = new AmberApiServer.MNano();
      //expect(instance).to.be();
    });

  });

}));
