/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmberApiServer.MNanoBackend();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MNanoBackend', function() {
    it('should create an instance of MNanoBackend', function() {
      // uncomment below and update the code to test MNanoBackend
      //var instane = new AmberApiServer.MNanoBackend();
      //expect(instance).to.be.a(AmberApiServer.MNanoBackend);
    });

    it('should have the property versionNumber (base name: "VersionNumber")', function() {
      // uncomment below and update the code to test the property versionNumber
      //var instane = new AmberApiServer.MNanoBackend();
      //expect(instance).to.be();
    });

    it('should have the property mPatternMemory (base name: "m_PatternMemory")', function() {
      // uncomment below and update the code to test the property mPatternMemory
      //var instane = new AmberApiServer.MNanoBackend();
      //expect(instance).to.be();
    });

    it('should have the property mInitComplete (base name: "m_InitComplete")', function() {
      // uncomment below and update the code to test the property mInitComplete
      //var instane = new AmberApiServer.MNanoBackend();
      //expect(instance).to.be();
    });

    it('should have the property mPatternLength (base name: "m_PatternLength")', function() {
      // uncomment below and update the code to test the property mPatternLength
      //var instane = new AmberApiServer.MNanoBackend();
      //expect(instance).to.be();
    });

    it('should have the property mLearningIsOn (base name: "m_LearningIsOn")', function() {
      // uncomment below and update the code to test the property mLearningIsOn
      //var instane = new AmberApiServer.MNanoBackend();
      //expect(instance).to.be();
    });

    it('should have the property mNumOfPatternsClustered (base name: "m_NumOfPatternsClustered")', function() {
      // uncomment below and update the code to test the property mNumOfPatternsClustered
      //var instane = new AmberApiServer.MNanoBackend();
      //expect(instance).to.be();
    });

  });

}));
