/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmberApiServer.MNCP();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MNCP', function() {
    it('should create an instance of MNCP', function() {
      // uncomment below and update the code to test MNCP
      //var instane = new AmberApiServer.MNCP();
      //expect(instance).to.be.a(AmberApiServer.MNCP);
    });

    it('should have the property versionNumber (base name: "VersionNumber")', function() {
      // uncomment below and update the code to test the property versionNumber
      //var instane = new AmberApiServer.MNCP();
      //expect(instance).to.be();
    });

    it('should have the property numOfFeatures (base name: "NumOfFeatures")', function() {
      // uncomment below and update the code to test the property numOfFeatures
      //var instane = new AmberApiServer.MNCP();
      //expect(instance).to.be();
    });

    it('should have the property mNumericFormat (base name: "m_NumericFormat")', function() {
      // uncomment below and update the code to test the property mNumericFormat
      //var instane = new AmberApiServer.MNCP();
      //expect(instance).to.be();
    });

    it('should have the property mPercentVariation (base name: "m_PercentVariation")', function() {
      // uncomment below and update the code to test the property mPercentVariation
      //var instane = new AmberApiServer.MNCP();
      //expect(instance).to.be();
    });

    it('should have the property mAccuracy (base name: "m_Accuracy")', function() {
      // uncomment below and update the code to test the property mAccuracy
      //var instane = new AmberApiServer.MNCP();
      //expect(instance).to.be();
    });

    it('should have the property mStreamingWindowSize (base name: "m_StreamingWindowSize")', function() {
      // uncomment below and update the code to test the property mStreamingWindowSize
      //var instane = new AmberApiServer.MNCP();
      //expect(instance).to.be();
    });

  });

}));
