/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MNCP', function() {
      beforeEach(function() {
        instance = new AmberApiServer.MNCP();
      });

      it('should create an instance of MNCP', function() {
        // TODO: update the code to test MNCP
        expect(instance).to.be.a(AmberApiServer.MNCP);
      });

      it('should have the property versionNumber (base name: "VersionNumber")', function() {
        // TODO: update the code to test the property versionNumber
        expect(instance).to.have.property('versionNumber');
        // expect(instance.versionNumber).to.be(expectedValueLiteral);
      });

      it('should have the property numOfFeatures (base name: "NumOfFeatures")', function() {
        // TODO: update the code to test the property numOfFeatures
        expect(instance).to.have.property('numOfFeatures');
        // expect(instance.numOfFeatures).to.be(expectedValueLiteral);
      });

      it('should have the property mNumericFormat (base name: "m_NumericFormat")', function() {
        // TODO: update the code to test the property mNumericFormat
        expect(instance).to.have.property('mNumericFormat');
        // expect(instance.mNumericFormat).to.be(expectedValueLiteral);
      });

      it('should have the property mPercentVariation (base name: "m_PercentVariation")', function() {
        // TODO: update the code to test the property mPercentVariation
        expect(instance).to.have.property('mPercentVariation');
        // expect(instance.mPercentVariation).to.be(expectedValueLiteral);
      });

      it('should have the property mAccuracy (base name: "m_Accuracy")', function() {
        // TODO: update the code to test the property mAccuracy
        expect(instance).to.have.property('mAccuracy');
        // expect(instance.mAccuracy).to.be(expectedValueLiteral);
      });

      it('should have the property mStreamingWindowSize (base name: "m_StreamingWindowSize")', function() {
        // TODO: update the code to test the property mStreamingWindowSize
        expect(instance).to.have.property('mStreamingWindowSize');
        // expect(instance.mStreamingWindowSize).to.be(expectedValueLiteral);
      });

    });
  });

}));
