/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MRecentTimes', function() {
      beforeEach(function() {
        instance = new AmberApiServer.MRecentTimes();
      });

      it('should create an instance of MRecentTimes', function() {
        // TODO: update the code to test MRecentTimes
        expect(instance).to.be.a(AmberApiServer.MRecentTimes);
      });

      it('should have the property versionNumber (base name: "VersionNumber")', function() {
        // TODO: update the code to test the property versionNumber
        expect(instance).to.have.property('versionNumber');
        // expect(instance.versionNumber).to.be(expectedValueLiteral);
      });

      it('should have the property mValues (base name: "m_Values")', function() {
        // TODO: update the code to test the property mValues
        expect(instance).to.have.property('mValues');
        // expect(instance.mValues).to.be(expectedValueLiteral);
      });

    });
  });

}));
