/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmberApiServer.MTraining();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MTraining', function() {
    it('should create an instance of MTraining', function() {
      // uncomment below and update the code to test MTraining
      //var instane = new AmberApiServer.MTraining();
      //expect(instance).to.be.a(AmberApiServer.MTraining);
    });

    it('should have the property versionNumber (base name: "VersionNumber")', function() {
      // uncomment below and update the code to test the property versionNumber
      //var instane = new AmberApiServer.MTraining();
      //expect(instance).to.be();
    });

    it('should have the property mGeometricPlotY (base name: "m_GeometricPlotY")', function() {
      // uncomment below and update the code to test the property mGeometricPlotY
      //var instane = new AmberApiServer.MTraining();
      //expect(instance).to.be();
    });

    it('should have the property mGeometricPlotX (base name: "m_GeometricPlotX")', function() {
      // uncomment below and update the code to test the property mGeometricPlotX
      //var instane = new AmberApiServer.MTraining();
      //expect(instance).to.be();
    });

    it('should have the property mClusterGrowth (base name: "m_ClusterGrowth")', function() {
      // uncomment below and update the code to test the property mClusterGrowth
      //var instane = new AmberApiServer.MTraining();
      //expect(instance).to.be();
    });

    it('should have the property mAnomalyIndexes (base name: "m_AnomalyIndexes")', function() {
      // uncomment below and update the code to test the property mAnomalyIndexes
      //var instane = new AmberApiServer.MTraining();
      //expect(instance).to.be();
    });

  });

}));
