/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PostAuth2Response', function() {
      beforeEach(function() {
        instance = new AmberApiServer.PostAuth2Response();
      });

      it('should create an instance of PostAuth2Response', function() {
        // TODO: update the code to test PostAuth2Response
        expect(instance).to.be.a(AmberApiServer.PostAuth2Response);
      });

      it('should have the property idToken (base name: "idToken")', function() {
        // TODO: update the code to test the property idToken
        expect(instance).to.have.property('idToken');
        // expect(instance.idToken).to.be(expectedValueLiteral);
      });

      it('should have the property refreshToken (base name: "refreshToken")', function() {
        // TODO: update the code to test the property refreshToken
        expect(instance).to.have.property('refreshToken');
        // expect(instance.refreshToken).to.be(expectedValueLiteral);
      });

      it('should have the property expiresIn (base name: "expiresIn")', function() {
        // TODO: update the code to test the property expiresIn
        expect(instance).to.have.property('expiresIn');
        // expect(instance.expiresIn).to.be(expectedValueLiteral);
      });

      it('should have the property tokenType (base name: "tokenType")', function() {
        // TODO: update the code to test the property tokenType
        expect(instance).to.have.property('tokenType');
        // expect(instance.tokenType).to.be(expectedValueLiteral);
      });

    });
  });

}));
