/**
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AmberApiServer.StreamStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StreamStatus', function() {
    it('should create an instance of StreamStatus', function() {
      // uncomment below and update the code to test StreamStatus
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be.a(AmberApiServer.StreamStatus);
    });

    it('should have the property clusterCount (base name: "clusterCount")', function() {
      // uncomment below and update the code to test the property clusterCount
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be();
    });

    it('should have the property progress (base name: "progress")', function() {
      // uncomment below and update the code to test the property progress
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be();
    });

    it('should have the property retryCount (base name: "retryCount")', function() {
      // uncomment below and update the code to test the property retryCount
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be();
    });

    it('should have the property streamingWindowSize (base name: "streamingWindowSize")', function() {
      // uncomment below and update the code to test the property streamingWindowSize
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be();
    });

    it('should have the property totalInferences (base name: "totalInferences")', function() {
      // uncomment below and update the code to test the property totalInferences
      //var instane = new AmberApiServer.StreamStatus();
      //expect(instance).to.be();
    });

  });

}));
