/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('StreamStatus', function() {
      beforeEach(function() {
        instance = new AmberApiServer.StreamStatus();
      });

      it('should create an instance of StreamStatus', function() {
        // TODO: update the code to test StreamStatus
        expect(instance).to.be.a(AmberApiServer.StreamStatus);
      });

      it('should have the property state (base name: "state")', function() {
        // TODO: update the code to test the property state
        expect(instance).to.have.property('state');
        // expect(instance.state).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property progress (base name: "progress")', function() {
        // TODO: update the code to test the property progress
        expect(instance).to.have.property('progress');
        // expect(instance.progress).to.be(expectedValueLiteral);
      });

      it('should have the property clusterCount (base name: "clusterCount")', function() {
        // TODO: update the code to test the property clusterCount
        expect(instance).to.have.property('clusterCount');
        // expect(instance.clusterCount).to.be(expectedValueLiteral);
      });

      it('should have the property retryCount (base name: "retryCount")', function() {
        // TODO: update the code to test the property retryCount
        expect(instance).to.have.property('retryCount');
        // expect(instance.retryCount).to.be(expectedValueLiteral);
      });

      it('should have the property streamingWindowSize (base name: "streamingWindowSize")', function() {
        // TODO: update the code to test the property streamingWindowSize
        expect(instance).to.have.property('streamingWindowSize');
        // expect(instance.streamingWindowSize).to.be(expectedValueLiteral);
      });

      it('should have the property totalInferences (base name: "totalInferences")', function() {
        // TODO: update the code to test the property totalInferences
        expect(instance).to.have.property('totalInferences');
        // expect(instance.totalInferences).to.be(expectedValueLiteral);
      });

    });
  });

}));
