/*
 * Amber API Server
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmberApiServer);
  }
}(this, function(expect, AmberApiServer) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Version', function() {
      beforeEach(function() {
        instance = new AmberApiServer.Version();
      });

      it('should create an instance of Version', function() {
        // TODO: update the code to test Version
        expect(instance).to.be.a(AmberApiServer.Version);
      });

      it('should have the property release (base name: "release")', function() {
        // TODO: update the code to test the property release
        expect(instance).to.have.property('release');
        // expect(instance.release).to.be(expectedValueLiteral);
      });

      it('should have the property apiVersion (base name: "api-version")', function() {
        // TODO: update the code to test the property apiVersion
        expect(instance).to.have.property('apiVersion');
        // expect(instance.apiVersion).to.be(expectedValueLiteral);
      });

      it('should have the property builder (base name: "builder")', function() {
        // TODO: update the code to test the property builder
        expect(instance).to.have.property('builder');
        // expect(instance.builder).to.be(expectedValueLiteral);
      });

      it('should have the property expertApi (base name: "expert-api")', function() {
        // TODO: update the code to test the property expertApi
        expect(instance).to.have.property('expertApi');
        // expect(instance.expertApi).to.be(expectedValueLiteral);
      });

      it('should have the property expertCommon (base name: "expert-common")', function() {
        // TODO: update the code to test the property expertCommon
        expect(instance).to.have.property('expertCommon');
        // expect(instance.expertCommon).to.be(expectedValueLiteral);
      });

      it('should have the property nanoSecure (base name: "nano-secure")', function() {
        // TODO: update the code to test the property nanoSecure
        expect(instance).to.have.property('nanoSecure');
        // expect(instance.nanoSecure).to.be(expectedValueLiteral);
      });

      it('should have the property swaggerUi (base name: "swagger-ui")', function() {
        // TODO: update the code to test the property swaggerUi
        expect(instance).to.have.property('swaggerUi');
        // expect(instance.swaggerUi).to.be(expectedValueLiteral);
      });

    });
  });

}));
